### ISSUE TITLE
Help wanted - apply within

### ISSUE THREAD

**Issue by Danack** [Imagick/imagick#162]
Hello there,

Let me introduce myself - I'm Daniel, and I've been maintaining for Imagick for two years. Although I'm (just about) capable of doing the bug fixes and code changes needed to make Imagick work against new versions of PHP, I'm really struggling to keep the documentation up-to-date, and I don't have anywhere near enough time to improve it to where it needs to be.

Does anyone want to contribute to this project? If so, super awesome! If not - well okay, but I'm not going to care about people whining about the documentation....

The main things that need to be done to document Imagick well enough for people to start migrating to  ImageMagick 7 rather than ImagickMagick 6 are:
- Mark the functions that are removed in ImageMagick 7 as deprecated when Imagick is built against ImageMagick 6.x. This is mostly just a case of going through the code and adding the appropriate deprecation notice wherever there is a `#if MagickLibVersion < 0x700` in the code. The difficult bit is figuring out what information to put in the deprecation notice e.g. whether a function has just been removed because it was terrible, or whether the functionality is still available through a different function name.

A good example of this is all of the functionality relating to setImageBias has been migrated to the [morphology function](http://phpimagick.com/Imagick/morphology)
- Document the functions removed, as well the changed constants. This is actually not a trivial thing to do, as not all of the constants changed are documented that well....
- Put more links from the PHP Imagick manual to http://phpimagick.com/ - as pictures speak a 1000 words a lot of the time.

So, is there anyone out there who uses Imagick that has the time and the desire to contribute something back? If so, either get in touch through this issue, or talk to me on twitter https://twitter.com/MrDanack or email danack@basereality.com

If you say whether you want to contribute:
- code - i.e.  submit PRs for the C code itself
- documentation - write specific bits of documentation in php.net's docbook format
- research - just go around the ImageMagick documentation and figure stuff out....this is actually a massive time consumer as the documentation is kind of 'fragmented'.

That would let me know which direction to point you in.

But in general the open tickets are on this repo's issues, and the PHP bug list:
https://github.com/mkoppanen/imagick/issues
https://bugs.php.net/search.php?cmd=display&package_name[]=imagick

**Comment by Danack** [comment]
For reference, these changes need to be documented in the PHP manual also: http://legacy.imagemagick.org/api/deprecate.php

**Comment by eallenOP** [comment]
I have some students looking to help out with documentation for some projects. They start in a month. They aren't programming experts as they have had one year of C# and some web, but can do leg-work and writing. Is there any way they can help?

**Comment by Danack** [comment]
@eallenOP  sorry for the slow response and thanks for the offer. Realistically though, unless they have experience with either Imagick or ImageMagick, people who are newish to programming aren't going to be in a position to offer that much assistance without at least some guidance..

What I really need is someone who uses the library a lot, or who uses ImageMagick itself, to be able to figure out what bug reports mean, or what the changes upstream are, and so tell me what changes need to be made.

**Comment by Y0lk** [comment]
Hey! First of all, I appreciate all the work you've done on Imagick. Now, let me introduce myself very quickly. 

I've been using Imagick for many years now in a system that has to render big print files (that go up to 12 000px wide and more). Imagick has always worked well for us since the system is PHP-based. Not only do we actively use it (the system renders thousands of print files everyday), but we also regularly develop new stuff that uses imagick.

We've been doing a few tests recently with ImageMagick 7 and ran into problems. That's when I found this post. I'd be interested in contributing (on all aspects)! I'm certainly not an ImageMagick expert, but I've developed quite a bit of code with Imagick and done quite a lot of research on ImageMagick itself.

Let me know what you think!

Just some more info, we use Imagick on both Windows and Unix-based servers, 32bit and 64bit, if that can help with testing.

**Comment by Danack** [comment]
Hi @Y0lk,

Thanks for the offer - I gratefully accept!

A really good place to start helping would be with the documentation issues that need addressing, or just in general going through the entries in http://php.net/manual/en/book.imagick.php and finding any entries that have either no info, or could do with more info.

For example some issues that could do with some writing for are:

https://github.com/mkoppanen/imagick/issues?q=is%3Aissue+is%3Aopen+label%3ADocumentation

https://bugs.php.net/bug.php?id=54447
https://bugs.php.net/bug.php?id=64784
https://bugs.php.net/bug.php?id=71074
https://bugs.php.net/bug.php?id=73587
https://bugs.php.net/bug.php?id=73855

The editor is online at: https://edit.php.net/ though it can be easier to click 'edit page' in the top right, to jump straight to editing a page. Just in case someone else doesn't accept the changes you make there, if you use anonymous login, and remember either what userId you are, or what the 'patch' name is when you save it, and ping that to me, I should be able to merge them.

Additionally, starting a migration guide for users going from ImageMagick 6 to 7 would be a big task that needs doing.

> We've been doing a few tests recently with ImageMagick 7 and ran into problems.

If you have any reproducible errors, please open an issue for those.

**Comment by Y0lk** [comment]
Hi @Danack,

Thanks for all that info, started going through it. 
Most of the problems I ran into with ImageMagick 7 are related to alpha. I'm guessing that's because of the changes they made to opacity/alpha. When I noticed that, I decided to hold off on upgrading for now. I'll be doing more tests soon so I'll report issues I find.

As for writing the migration guide, I should be able to help with that once I start looking into migrating my own system.

**Comment by jdabs** [comment]
Hi @Danack and @Y0lk ,
I'm going through the documentation lately and wrapping my head around the bigger picture. I submitted 2 patches last night under an anon account for clarity.

I plan on continuing on any clarity fixes and filling out any function/api references that are missing or not filled out.

**Comment by Danack** [comment]
I'm going to close this. 

One of the big problems facing open source is that curating that list of stuff that needs to be worked on, and trying to instruct people in how to do it, is incredibly boring and takes longer than just doing the work.
