### ISSUE TITLE
Move Imagick to it's own organisation in Github

### ISSUE THREAD

**Issue by mkoppanen** [Imagick/imagick#172]
As Imagick is developed by larger group of contributors it should live under it's own organisation in Github. This would allow collecting possibly related projects under one umbrella and manage contributors in easier way.

Opinions?

**Comment by Danack** [comment]
Sounds like a good idea.

I actually don't know that much about Github organisations. I should read up on them. 

I believe I've grabbed control of "Imagick", "phppecl" and "php-pecl", which mysteriously were all available. One of them might be appropriate.

Also, you appear to have a new tailor?

Actually seeing as we're within the same country for once - do you fancy a beer?
 https://twitter.com/MrDanack

**Comment by mkoppanen** [comment]
Heh, following up tiny bit late. Better late than ever I guess. Do you prefer the move to the imagick organisation? I see you are the main maintainer at the moment and it doesn’t make sense for the extension to live under my personal account.

Also, re: beer. Ping me on https://twitter.com/mkoppanen

**Comment by Danack** [comment]
Yep. The Imagick org would be a sensible place for it.

I've been toying with the idea of adding some helper functions in userland, and having those both under Imagick would be sensible.

You should be able to move it there now, as you should have the correct permissions to create repos there? Let me know if it gives you an error message.

**Comment by mkoppanen** [comment]
This has been resolved
