### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by Danack** [Imagick/imagick#271]
There are changes required to support PHP 8 which is the current default branch of PHP src.

I'm not planning to do these at least until the 2nd half of 2019.

**Comment by strarsis** [comment]
Any news on this?
Using [pickle](https://github.com/FriendsOfPHP/pickle) to install `imagick` for PHP 8.0.0RC2 currently fails:
````
/tmp/imagick/imagick-3.4.4/php_imagick_file.h:61:108: error: expected ';', ',' or ')' before 'TSRMLS_DC'
[...]
````

**Comment by Danack** [comment]
> I'm not planning to do these at least until the 2nd half of 2019.

Well, I wasn't wrong.

**Comment by PhoenixPeca** [comment]
I'm having the same issue.. :'(

**Comment by strarsis** [comment]
@Danack: Any plans for adding PHP 8 support in the near future? What adjustments have to be done to make it possible? Anything where I or others can contribute?

**Comment by josenobile** [comment]
WordPress 5.6 is out as stable, PHP 8.0 is stable, We need Imagick in PHP 8.0

This issue should be reopened @Danack

**Comment by TimWolla** [comment]
> This issue should be reopened @Danack

No, because it is a duplicate of #358.

**Comment by Danack** [comment]
> Anything where I or others can contribute?

@strarsis I'll write more on phpimagick.com but basically, I think OpenSource is unsustainable currently. The work required is quite tedious and quite annoying, and there is very little reward for doing it.

For it to be sustainable companies (not people) need to start paying for the software they rely on. The amount of money that OpenSource needs is tiny, e.g. Imagick would be fully funded if every company that used it paid $1 a year. It would be hilariously over funded if companies paid $1 a month.

I have no idea how we go from where we are to a sustainable place but probably the announcement of Github that companies can now support OpenSource developers will be part of it.

Please ask your company to sponsor development of this project through: https://github.com/sponsors/Danack

**Comment by Foddy** [comment]
Another reason to hate 2020 … 😅

**Comment by omexlu** [comment]
When be a PECL package avaible for php8, thanks?

**Comment by bally86** [comment]
Does anybody know how to compile a dll for a PHP8 installation on a Windows machine?
Is there any manual available?
