### ISSUE TITLE
Bad stabililty in 3.4.4RC1

### ISSUE THREAD

**Issue by remicollet** [Imagick/imagick#275]
3.4.4RC1 have been released on PECL with "stable" while should be "beta"

Good candidate to re-upload with proper flag

**Comment by Danack** [comment]
ugh.

What should I do. I can't re-upload the same version as pecl forbids it.

I can upload RC2, and could set 'beta' for stability. Then if all looks good, do  actual release tomorrow?

**Comment by remicollet** [comment]
You can delete RC1 and then upload RC2

(else "pecl install imagick" will pull RC1)


P.S. follow the "pen" button near the "edit maintainers" link

**Comment by remicollet** [comment]
> Then if all looks good, do actual release tomorrow?

Perhaps can wait a few days.... for more feedback

**Comment by remicollet** [comment]
FYI, I run various build of RC2, everything seems OK
* Fedora 27-30
* RHEL 6, 7 and 8-beta
* i386, x86_64
* NTS, ZTS

Also a Fedora 31 scratch build (more arches)
http://koji.fedoraproject.org/koji/taskinfo?taskID=34235403

**Comment by remicollet** [comment]
> Then if all looks good, do actual release tomorrow?

2 weeks... perhaps time for the "stable"  3.4.4 ?

**Comment by Danack** [comment]
I'm going to merge the testing_ALPHACHANNEL_REMOVE branch. I don't think that needs another RC (famous last words), though very annoyingly quite a few of the tests have broken due to a change on Travis.

Also, there is one more thing that I'm setting up to include in the release notes.

**Comment by Danack** [comment]
stable release was released.
