### ISSUE TITLE
not working under PHP-FPM

### ISSUE THREAD

**Issue by starchild** [Imagick/imagick#285]
We're running 3.4.3, on cloudlinux 7.6, PHP 7.x

When ever we have FPM activated, imagick fails to create the image.  If I switch FPM off, the image will show.

I've searched high and low and can't find a solution.  Does anyone have a fix for this?

Thank you.

**Comment by Danack** [comment]
You don't give enough information to describe what you are experiencing for anyone to be able to help.

In particular what does:

> If I switch FPM off, the image will show.

This mean?

**Comment by Danack** [comment]
I'm going to close this as there's no info.

**Comment by starchild** [comment]
Sorry, I thought it self explanatory.

If FPM is enabled on a site, then IMagick doesn't work for that site.  When I look at what should be the image, it gives a 404.

If i then disable FPM on that site, the image will show up.

Does that make sense?

**Comment by Danack** [comment]
> If FPM is enabled on a site, .... If i then disable FPM then.

I don't know what either of those mean. It might be clear to you, but you can see exactly which tool or config file you're using to do that, but I don't recognise that terminology or understand what it would mean.

Most webservers can be configured to use PHP in one of three ways:

* cgi - which is quite old and slow so no-one uses.
* fastcgi - where PHP is run as PHP-FPM as it's own process and listens for fcgi requests.
* apache - which is used by Apache to run PHP within the Apache memory.

When you say 'i then disable FPM' that means that you're changing something.....but from what to what. How are you disabling it? Are you editing a config file? Are you using a different docker container base image? Are you recomping PHP from src?

> When I look at what should be the image, it gives a 404.

tbh, that sounds like you're switching between two different config files and one of them isn't setup to serve images.

**Comment by starchild** [comment]
In cpanel, you can enable or disable PHP-FPM on any site.  As you have pointed out above, it is a tweak to fastcgi essentially and stores queries etc in a kind of cached memory (from what I understand anyway). It's fairly commonplace in WHM/Cpanel servers, and is turned on/off by just clicking a button and WHM does the rest.  It can be done on a site by site basis or server wide.

Given how commonplace it is, I guess I just thought that this issue would have been encountered before.

I'll pass your thoughts about the two config files on to our server team, it might help them. Thank you.

**Comment by starchild** [comment]
OK, FWIW, I found the issue and it wasn't quite within Imagick itself, but rather an exe() function being disabled when FPM was enabled.

Hopefully this will help someone else having similar issues.
