### ISSUE TITLE
Imagick and FPM

### ISSUE THREAD

**Issue by starchild** [Imagick/imagick#286]
Please see https://github.com/Imagick/imagick/issues/285 which was closed without even letting me reply.

Thank you.

**Comment by Danack** [comment]
For future reference, closing issues due to lack of information and then re-opening them when more info arrives isn't a big deal.

But opening duplicate issues is pretty frowned upon.

**Comment by starchild** [comment]
ok, good to know - thanks.  Kind of felt like I was shut down pretty quickly for asking a genuine question though...
