### ISSUE TITLE
Version 3.4.4 with ImageMagick 6: setImageOpacity is deprecated without alternative

### ISSUE THREAD

**Issue by samdark** [Imagick/imagick#288]
3.4.4 deprecated `setImageOpacity()` but when used with ImageMagick 6 there's no `setImageAlpha()` available since it was added in ImageMagick 7.

Issue could be solved with:

1. Removing deprecation error.
2. Adjusting readme noting that 3.4.4 does't support ImageMagick 6 anymore.

**Comment by Danack** [comment]
What's the actual problem here?

setImageOpacity is deprecated isn't going to be around forever.

If you want to keep using it for now, you can silence the deprecation notice with an `@`.

**Comment by samdark** [comment]
OK. Makes sense. I guess it's better to be fixed in Imagine: https://github.com/avalanche123/Imagine/issues/715

**Comment by samdark** [comment]
The problem is that it doesn't silence with `@` https://ci.appveyor.com/project/avalanche123/imagine/builds/24916894/job/poa3lc6cs6kxae9i#L184. Is it doing correct deprecation level message?

**Comment by samdark** [comment]
Ah, that is PHPUnit.

**Comment by Danack** [comment]
yeah, this is how deprecation notices work. 

btw it's probably not appropriate to open multiple issues for the same problem across different repos as it means at least one persons time is going to be wasted.

**Comment by samdark** [comment]
I wasn't sure about where is the best place to fix the issue so asked all parties. Probably should have been done in a single issue but preferences about that vary from project to project.
