### ISSUE TITLE
Configuring error on masOS Mojave

### ISSUE THREAD

**Issue by Jiri-Mihal** [Imagick/imagick#289]
Hello,

I can't install Image Magick. I've tried PECL and compilation from source. Both attempts end same. My setup is:

➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132

➜  ~ php -v
PHP 7.3.6 (cli) (built: May 31 2019 23:38:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6, Copyright (c) 1999-2018, by Zend Technologies

➜  ~ pecl version
PEAR Version: 1.10.9
PHP Version: 7.3.6
Zend Engine Version: 3.3.6
Running on: Darwin Jiris-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

PECL attempt:

➜  ~ pecl install imagick    
downloading imagick-3.4.4.tgz ...
Starting to download imagick-3.4.4.tgz (253,434 bytes)
.....................................................done: 253,434 bytes
19 source files, building
running: phpize
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
Please provide the prefix of ImageMagick installation [autodetect] : 
building in /private/tmp/pear/install/pear-build-jirimihalLLRJU8/imagick-3.4.4
running: /private/tmp/pear/install/imagick/configure --with-php-config=/usr/local/opt/php/bin/php-config --with-imagick
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin18.6.0
checking host system type... x86_64-apple-darwin18.6.0
checking target system type... x86_64-apple-darwin18.6.0
checking for PHP prefix... /usr/local/Cellar/php/7.3.6
checking for PHP includes... -I/usr/local/Cellar/php/7.3.6/include/php -I/usr/local/Cellar/php/7.3.6/include/php/main -I/usr/local/Cellar/php/7.3.6/include/php/TSRM -I/usr/local/Cellar/php/7.3.6/include/php/Zend -I/usr/local/Cellar/php/7.3.6/include/php/ext -I/usr/local/Cellar/php/7.3.6/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php/7.3.6/pecl/20180731
checking for PHP installed headers prefix... /usr/local/Cellar/php/7.3.6/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable the imagick extension... yes, shared
checking for pkg-config... /usr/local/bin/pkg-config
checking ImageMagick MagickWand API configuration program... checking Testing /usr/local/bin/MagickWand-config... Doesn't exist
checking Testing /usr/bin/MagickWand-config... Doesn't exist
checking Testing /usr/sbin/bin/MagickWand-config... Doesn't exist
checking Testing /opt/bin/MagickWand-config... Doesn't exist
checking Testing /opt/local/bin/MagickWand-config... Doesn't exist
configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.
ERROR: `/private/tmp/pear/install/imagick/configure --with-php-config=/usr/local/opt/php/bin/php-config --with-imagick' failed

Compilation from source attempt:

➜  imagick-3.4.4 phpize
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731

➜  imagick-3.4.4 ./configure
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin18.6.0
checking host system type... x86_64-apple-darwin18.6.0
checking target system type... x86_64-apple-darwin18.6.0
checking for PHP prefix... /usr/local/Cellar/php/7.3.6
checking for PHP includes... -I/usr/local/Cellar/php/7.3.6/include/php -I/usr/local/Cellar/php/7.3.6/include/php/main -I/usr/local/Cellar/php/7.3.6/include/php/TSRM -I/usr/local/Cellar/php/7.3.6/include/php/Zend -I/usr/local/Cellar/php/7.3.6/include/php/ext -I/usr/local/Cellar/php/7.3.6/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php/7.3.6/pecl/20180731
checking for PHP installed headers prefix... /usr/local/Cellar/php/7.3.6/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable the imagick extension... yes, shared
checking for pkg-config... /usr/local/bin/pkg-config
checking ImageMagick MagickWand API configuration program... checking Testing /usr/local/bin/MagickWand-config... Doesn't exist
checking Testing /usr/bin/MagickWand-config... Doesn't exist
checking Testing /usr/sbin/bin/MagickWand-config... Doesn't exist
checking Testing /opt/bin/MagickWand-config... Doesn't exist
checking Testing /opt/local/bin/MagickWand-config... Doesn't exist
configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.

Any idea? Thanks.

**Comment by Danack** [comment]
It's telling you it can't find ImageMagick.

```
checking ImageMagick MagickWand API configuration program... checking Testing /usr/local/bin/MagickWand-config... Doesn't exist
checking Testing /usr/bin/MagickWand-config... Doesn't exist
checking Testing /usr/sbin/bin/MagickWand-config... Doesn't exist
checking Testing /opt/bin/MagickWand-config... Doesn't exist
checking Testing /opt/local/bin/MagickWand-config... Doesn't exist
configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.
```

ImageMagick is the library that does the image processing. The Imagick is just a wrapper to make it available in PHP.

**Comment by Jiri-Mihal** [comment]
@Danack Thank you for your help. So I've tried...

➜  ~ brew install imagemagick
➜  ~ pecl install imagick

...and voila, it works😀

I thought installing extension using the PECL should be enough to install the ImageMagick to PHP. It should install ImageMagick and PHP wrapper too, or not?

**Comment by Danack** [comment]
> It should install ImageMagick

No, if you're compiling it from source (which is what pecl does) then you're expected to install the dependencies yourself, as Imagick can't tell what version of ImageMagick you might want, or where to install it from.

It's package managers that will provide the dependencies for you.

**Comment by freonirons409** [comment]
I had this same issue and found that Brew created a symlink from the "/usr/local/Cellar/php/7.3.6/... "folder to the "usr/local/php..." folder but the folder it was symlinked to didnt actually exist--so when PECL was installing it could not do so because the symlinked folder did not exist---I created the pecl inside the php folder and it worked perfectly.

**Comment by RussellCao824** [comment]
> brew install imagemagick

really cool

**Comment by samsonasik** [comment]
> 
> ➜ ~ brew install imagemagick
> ➜ ~ pecl install imagick
> 
> ...and voila, it works😀
> 
> I thought installing extension using the PECL should be enough to install the ImageMagick to PHP. It should install ImageMagick and PHP wrapper too, or not?

@Jiri-Mihal that works! Thank you. Just add note that may usefull for others when found it, `pecl` need to use `sudo` to install the `imagick` in macOS Big Sur.

```bash
brew install imagemagick
sudo pecl install imagick
```

**Comment by vknowles-rv** [comment]
> @Jiri-Mihal that works! Thank you. Just add note that may usefull for others when found it, pecl need to use sudo to install the imagick in macOS Big Sur.

`sudo` should not be needed to install a pecl, nor should you be running or installing php via sudo.
