### ISSUE TITLE
ImageMagick-7.0.8-50-vc15-x64.zip

### ISSUE THREAD

**Issue by telatoa** [Imagick/imagick#293]
Hi,

I'm looking for the **ImageMagick-7.0.8-50-vc15-x64.zip** file in https://windows.php.net/downloads/pecl/deps/ site.

The last available one is **ImageMagick-7.0.7-11-vc15-x64.zip**.

Could you please tell when this file will be released and available in this site?

Thanks in advance.

Regards.

**Comment by Danack** [comment]
Sorry, I don't manage the windows.php.net build. Please can you ask on the main bugs.php.net site.

**Comment by telatoa** [comment]
Ok thank you.
