### ISSUE TITLE
Missing CDR delegate (uniconvertor)

### ISSUE THREAD

**Issue by volk234** [Imagick/imagick#306]
Hello.
Using ImageMagick (with uniconvertor delegate) I'm converting files from CDR to PNG perfectly like so:
`convert test.cdr test.png`

And this also works with php-imagick on Ubuntu 18.04 (dev server)
```
$im = new Imagick();
$im->readImage($file);
$im->setImageFormat('png');
```

But when i try to use php-imagick on Debian 9.11 (prod server) I get exception with `$im->readImage($file):`

> unable to open file `/tmp/magick-5293abjh6oxs46V': No such file or directory @ error/constitute.c/ReadImage/544

Uniconvertor is installed. Using of `convert test.cdr test.png` still works fine.

Ubuntu phpinfo()
![image](https://user-images.githubusercontent.com/22075711/69227590-e6531200-0ba3-11ea-968a-48bfbf947f71.png)

Debian phpinfo()
![image](https://user-images.githubusercontent.com/22075711/69227646-fbc83c00-0ba3-11ea-91e0-39d3b14bdf0b.png)

Php-imagick was installed by PECL.

**Comment by botzkobg** [comment]
Hi @volk234,

How are you executing the php script - from the console or apache/nginx is executing it? If it's apache/ngingx then may be you need to check the `systemd` configuration file for the service. If the service is configured with `PrivateTmp=yes` then your temp files are saved in `/tmp/systemd-private-HASH/tmp` and this could cause the reported error `/tmp/magick-5293abjh6oxs46V': No such file or directory`.

**Comment by volk234** [comment]
> Hi @volk234,
> 
> How are you executing the php script - from the console or apache/nginx is executing it? If it's apache/ngingx then may be you need to check the `systemd` configuration file for the service. If the service is configured with `PrivateTmp=yes` then your temp files are saved in `/tmp/systemd-private-HASH/tmp` and this could cause the reported error `/tmp/magick-5293abjh6oxs46V': No such file or directory`.

Thanks for response!
I reconfigured nginx.service and php7.2-fpm.service with `PrivateTmp=false` and got same error. 
I use Laravel, nginx, php-fpm. Other convertations to png (from psd, svg, tiff) work fine.

**Comment by botzkobg** [comment]
Hi @volk234 ,

my suggestion here will be to set a brake point in your code and to confirm the file really exists. If you do not see it there then the problem is not with `imagick`. If the file is there check that it has proper permissions.

**Comment by volk234** [comment]
```
 private function makeThumbnail($file, $directory = null)
    {
        if (!$directory) {
            $directory = File::dirname($file) . '/';
        }

        try {
            exec('chmod a+rw ' . $file);

            $name = File::name($file);
            $thumbnailPath = $directory . $name . '_thumbnail.png';
            $im = new Imagick();
            $im->readImage($file);
            $im->setImageFormat('png');
            $im->thumbnailImage(300, 300, true);
            $im->writeImage($thumbnailPath);

            return File::exists($thumbnailPath) ? $thumbnailPath : false;
        } catch (\Exception $e) {
            Log::error($e->getMessage());
            return null;
        }
    }
```
Source $file exists (/storage/test.cdr) and has `a+rw` permissions in this example. 
And there is no file `/tmp/magick-5293abjh6oxs46V`, which should produced by `$im->readImage($file)`  :(

**Comment by volk234** [comment]
Running exec with `2>&1` showed trace of error. 
```
exec('/usr/bin/uniconvertor /tmp/test.cdr /tmp/test.png 2>&1', $op);
dd($op);
```


> array:20 [▼
>   0 => "Traceback (most recent call last):"
>   1 => "  File "/usr/bin/uniconvertor", line 16, in <module>"
>   2 => "    uc2.uc2_run()"
>   3 => "  File "/usr/lib/uniconvertor-2.0rc4/uc2/__init__.py", line 43, in uc2_run"
>   4 => "    app = uc2_init()"
>   5 => "  File "/usr/lib/uniconvertor-2.0rc4/uc2/__init__.py", line 36, in uc2_init"
>   6 => "    app = UCApplication(_pkgdir)"
>   7 => "  File "/usr/lib/uniconvertor-2.0rc4/uc2/application.py", line 103, in __init__"
>   8 => "    self.appdata = UCData(self, cfgdir, check=check)"
>   9 => "  File "/usr/lib/uniconvertor-2.0rc4/uc2/uc2conf.py", line 47, in __init__"
>   10 => "    self.check_config_dirs()"
>   11 => "  File "/usr/lib/uniconvertor-2.0rc4/uc2/uc2conf.py", line 52, in check_config_dirs"
>   12 => "    fsutils.makedirs(self.app_config_dir)"
>   13 => "  File "/usr/lib/uniconvertor-2.0rc4/uc2/utils/fsutils.py", line 82, in makedirs"
>   14 => "    os.makedirs(get_sys_path(path))"
>   15 => "  File "/usr/lib/python2.7/os.py", line 150, in makedirs"
>   16 => "    makedirs(head, mode)"
>   17 => "  File "/usr/lib/python2.7/os.py", line 157, in makedirs"
>   18 => "    mkdir(name, mode)"
>   19 => "OSError: [Errno 13] Permission denied: '/var/www/.config'"
> ]

Nginx didn't have permissions for write to /var/www/. Fixed it and everything works fine.

Thanks!
