### ISSUE TITLE
Clarify if compatible with ImageMagick 7.x

### ISSUE THREAD

**Issue by amenk** [Imagick/imagick#315]
I was wondering if the PHP extension compatible with ImageMagick 7.0, as the readme states

> We strongly recommend upgrading to the latest version (currently 6.9.1) if at all possible.

**Comment by Danack** [comment]
Yes it works with both the 6.x and 7.x branches of Image Magick.

**Comment by amenk** [comment]
https://github.com/Imagick/imagick/pull/317
