### ISSUE TITLE
Issue around removed add_index_zval

### ISSUE THREAD

**Issue by gerben-van-eck** [Imagick/imagick#316]
I recently had issues using PHP 7.4.0 in Alpine Linux (https://github.com/codecasts/php-alpine/issues/88), in an attempt to resolve it I have built 7.4.1 packages, but this unfortunately did not resolve the issue.

Error received:
`
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' 
(tried: /usr/lib/php7/modules/imagick.so 
(Error relocating /usr/lib/php7/modules/imagick.so: add_index_zval: symbol not found), 
/usr/lib/php7/modules/imagick.so.so (Error loading shared library /usr/lib/php7/modules/imagick.so.so: No such file or directory)) in Unknown on line 0
`
The add_index_zval method is called on:
https://github.com/Imagick/imagick/blob/master/imagick_class.c#L6815

And other lines.

As I understand, my C/C++ knowledge is limited, the add_index_zval method has 'changed'.
https://github.com/php/php-src/pull/4250

At least leading to issues in the MS-SQL driver too

https://github.com/microsoft/msphpsql/issues/999

**Comment by Danack** [comment]
Hi Gerben,

The issue in msphpsql is a different one to the one you're seeing.

The error message is saying that the imagick extension was compiled against a version of PHP that had add_index_zval defined as a function, so it is expecting that symbol to be available when loading the library.

But apparently it's now a macro, so it's not available.

If you recompile Imagick for PHP 7.4 it "should just work". 

You say you think you're doing that.....but I'm guessing that some old build artefact is not being cleaned, or something else similar.

**Comment by gerben-van-eck** [comment]
I originally got this error when using the packages from the mentioned repository, PHP 7.4.0, so they were not built by me. In an attempt to fix the issue, I forked the repo and created 7.4.1 packages, and got the same error.
So the problem is likely different then just old build artifacts, but as there are not hundreds of people yelling, I agree it is likely that the imagick extension still builts against 7.4.
I'll further investigate the build scripts I guess, thanks for your reply.

**Comment by Danack** [comment]
> I agree it is likely that the imagick extension still builts against 7.4.

@gerben-van-eck  Actually, I think it's still trying to build against 7.3.x as the change was made in php src before 7.4.0 was released.

But yeah, likely a problem not for me to solve.
