### ISSUE TITLE
Load remote files within a docker alpine+php image

### ISSUE THREAD

**Issue by Xplouder** [Imagick/imagick#325]
Greetings,

Sorry for posting this here but I couldn't find a better place.

So my problem after hours of debug, resulted in this: PHP release **<= 7.1.20** works fine with Imagick against this snippet `php -r "new \Imagick('https://file-examples.com/wp-content/uploads/2017/10/file_example_JPG_100kB.jpg');"` however **> 7.1.20** the snippet always fail with
```
Fatal error: Uncaught ImagickException: no decode delegate for this image format `' @ error/constitute.c/ReadImage/560 in Command line code:1
Stack trace:
#0 Command line code(1): Imagick->__construct('https://file-ex...')
#1 {main}
  thrown in Command line code on line 1
```

I think it's not related to PHP version directly but with the imagemagick binaries that ships with the alpine version that holds every PHP image. Concluding that the snippet above always fails for `imagemagick 7.0.8-68` or higher (this version is present in PHP 7.1.21-fpm-alpine image).

-----------------------------------------------------------------------------------------

Here are some Dockerfiles what I said before:

PHP 7.1.20 
imagemagick 7.0.7-11
imagick extension version 3.4.4
alpine 3.7.0
result: exits with error code 1 meaning that the PHP script worked fine
```
FROM php:7.1.20-fpm-alpine

RUN set -eux; \
    apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS imagemagick-dev libtool \
    && export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
    && pecl install imagick-3.4.4 \
    && docker-php-ext-enable imagick \
    && apk add --no-cache --virtual .imagick-runtime-deps imagemagick \
    && apk del .phpize-deps

RUN set -eux; \
    php -r "new \Imagick('https://file-examples.com/wp-content/uploads/2017/10/file_example_JPG_100kB.jpg');" \
    && exit 1
```

PHP 7.1.21 
imagemagick 7.0.8-68
imagick extension version 3.4.4
alpine 3.8.1
result: ```Fatal error: Uncaught ImagickException: no decode delegate for this image format `' @ error/constitute.c/ReadImage/560 in Command line code:1```
```
FROM php:7.1.21-fpm-alpine

RUN set -eux; \
    apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS imagemagick-dev libtool \
    && export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
    && pecl install imagick-3.4.4 \
    && docker-php-ext-enable imagick \
    && apk add --no-cache --virtual .imagick-runtime-deps imagemagick \
    && apk del .phpize-deps

RUN set -eux; \
    php -r "new \Imagick('https://file-examples.com/wp-content/uploads/2017/10/file_example_JPG_100kB.jpg');" \
    && exit 1
```

PS: the same problem is reproducible against the lastest PHP version `php:7.4.5-fpm-alpine`

@michabbb @Danack Any thoughts? since it's similar to https://github.com/Imagick/imagick/issues/322, like... I'm missing something?

Thank you!

**Comment by michabbb** [comment]
as you mentioned me and my problem, you should have learned from my issue, that there are permission problems on os basis, deep inside alpine. it's not worth debugging that, as it is "bad practice" anyway. always fetch the remote file first, then do something with it. in that case you have control and know when something is wrong with the remote file.

**Comment by Danack** [comment]
@michabbb I can see you're trying to be helpful, but your phrasing is shite.

Instead of "you should have learned from my issue," if you had said "please note the details of my issue" it would have:

* removed the tone of disappointment.
* removed the tone of blame.

But yeah....I kind of agree about the worth of debugging issues on alpine.

**Comment by michabbb** [comment]
@Danack pardon? as he mentioned my issue, he "should have learned something" - yes, that is absolutely my point of view. and it clearly turned out: he did not learn anything from that issue, otherwise he would not have created "the same issue" again. holy 🐮 - people telling the truth don´t have many friends, I am used to that, don´t worry. but thanks for teaching me. 🙄

**Comment by Danack** [comment]
Well piss off then.

**Comment by Danack** [comment]
> Sorry for posting this here but I couldn't find a better place.

You're not the first person to say that. I don't use Alpine, so have never needed to open a bug report for it.

For funsies, I just tried to figure out where the right place is to open a bug report......and yeah, WOW! that's not easy.

So instead, I've opened a bug report about how hard it is to open bug reports: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11528

As it appears to be a permissions thing, I'm not going to investigate it as I don't feel like doing that, and it's not something to fix in this repo.

For the record - I don't recommend using Alpine for Imagick/ImageMagick.

Although there are great uses cases for alpine, particularly where you want to run tens of containers on a single CPU it's way less useful for ImageMagick.

The ImageMagick binaries are huge, so the difference in size between running IM on alpine vs debian slim are minimal. And imo the 'maintenance environment' for Debian is better, even if it's just for being able to open bugs....

I'm going to close this, and think about explicitly not supporting alpine as it seems to provide very little value.

**Comment by Xplouder** [comment]
@michabbb I have learned, however the "not worth debugging" is not satisfactory for me, especially finding this still happening in the latest releases. Anyway, just ignore my mention. :facepalm: 

@Danack Thank you for your response and the bug report open. Change the image to Debian is not an option now due to legacy stuff, but ill keep it in mind. :wink: 

Guess I found a workaround:
```
$imagick = new \Imagick();
$url = 'https://file-examples.com/wp-content/uploads/2017/10/file_example_JPG_100kB.jpg';

$imagick->readImageFile(fopen($url, 'rb')); // fails in the cases i mentioned in original post
$imagick->readImageBlob(file_get_contents($url)); // always work
```

For some reason, the `readImageFile()` (which is probably equivalent to using Imagick constructor) do not work, however `readImageBlob()` works fine always. Any idea why they both have different behaviors?

**Comment by Danack** [comment]
They take different code paths internally. the read image blob uses php memory to download the file into, For readImageFile, ImageMagick is doing the download itself, and probably writing the download to a temporary file. 

Or at least trying to, and failing because the file permissions for that write are not setup properly.

**Comment by Xplouder** [comment]
Yeh probably...Since this seems to be an Alpine problem, you think https://gitlab.alpinelinux.org/alpine/aports/-/issues is the best place to create an issue? Thanks again!

**Comment by Danack** [comment]
Yep, that's the one.

**Comment by samdharris** [comment]
> @michabbb I have learned, however the "not worth debugging" is not satisfactory for me, especially finding this still happening in the latest releases. Anyway, just ignore my mention. 🤦
> 
> @Danack Thank you for your response and the bug report open. Change the image to Debian is not an option now due to legacy stuff, but ill keep it in mind. 😉
> 
> Guess I found a workaround:
> 
> ```
> $imagick = new \Imagick();
> $url = 'https://file-examples.com/wp-content/uploads/2017/10/file_example_JPG_100kB.jpg';
> 
> $imagick->readImageFile(fopen($url, 'rb')); // fails in the cases i mentioned in original post
> $imagick->readImageBlob(file_get_contents($url)); // always work
> ```
> 
> For some reason, the `readImageFile()` (which is probably equivalent to using Imagick constructor) do not work, however `readImageBlob()` works fine always. Any idea why they both have different behaviors?

just coming here to say thanks for this! I've come across this issue today after code that's worked for 3+ years suddenly stopped working after updating our runtime.
