### ISSUE TITLE
Failed test with IM 6.9.11-20

### ISSUE THREAD

**Issue by remicollet** [Imagick/imagick#329]
```
TEST 265/275 [tests/279_ImagickDraw_setTextInterlineSpacing.phpt]
========DIFF========
001+ textInterlineSpacing of 16 only resulted in extra height of 0
========DONE========
FAIL Test ImagickDraw:: setTextInterlineSpacing [tests/279_ImagickDraw_setTextInterlineSpacing.phpt] 

```

**Comment by remicollet** [comment]
Could be related to https://github.com/ImageMagick/ImageMagick6/commit/77849ee5a5f0481e0bfd67f72f6b7e07c5d2ba46

**Comment by remicollet** [comment]
Reported as https://github.com/ImageMagick/ImageMagick6/issues/85

**Comment by Danack** [comment]
![MyJobIsDoneHere](https://user-images.githubusercontent.com/1505719/100279821-24c1a080-2f5f-11eb-98d7-effd80e7e585.png)
