### ISSUE TITLE
check parameter names

### ISSUE THREAD

**Issue by Danack** [Imagick/imagick#340]
Since calling with named parameters is a thing now, we need to check parameter names are sensible.

Probably need to generate them from stubs.

https://github.com/php/php-src/pull/5339

**Comment by Danack** [comment]
Dump of params count below.

Need to setup generating param info from stub before changing them.


x: 48 
y: 48 
CHANNEL: 37 
width: 21 
color: 21 
height: 20 
Imagick: 18 
radius: 16 
sigma: 12 
columns: 10 
rows: 10 
legacy: 8 
filename: 8 
x1: 8 
y1: 8 
fuzz: 7 
offset: 7 
name: 7 
threshold: 7 
ImagickDraw: 6 
COLORSPACE: 6 
bestfit: 5 
angle: 5 
CHANNELTYPE: 5 
value: 5 
pattern: 5 
degrees: 5 
blackPoint: 4 
whitePoint: 4 
index: 4 
alpha: 4 
format: 4 
GRAVITY: 4 
opacity: 4 
METRIC: 4 
key: 4 
antialias: 4 
x2: 4 
y2: 4 
arguments: 3 
fill: 3 
invert: 3 
artifact: 3 
text: 3 
COMPOSITE: 3 
dither: 3 
xResolution: 3 
yResolution: 3 
gamma: 3 
rx: 3 
ry: 3 
sx: 3 
sy: 3 
ex: 3 
ey: 3 
imageContents: 2 
fp: 2 
gray: 2 
values: 2 
handle: 2 
font: 2 
pointsize: 2 
bordercolor: 2 
target: 2 
passphrase: 2 
map: 2 
stack: 2 
comment: 2 
brightness: 2 
saturation: 2 
hue: 2 
blur: 2 
depth: 2 
iterations: 2 
IMGTYPE: 2 
serverName: 2 
pathname: 2 
inside: 2 
sharpen: 2 
EVALUATE: 2 
magnitude: 2 
profile: 2 
numColors: 2 
treeDepth: 2 
measureError: 2 
INTERLACE: 2 
contrast: 2 
resource_type: 2 
similarity: 2 
similarity_threshold: 2 
metric: 2 
ImagickKernel: 2 
spacing: 2 
ox: 2 
oy: 2 
px: 2 
py: 2 
coordinateArray: 2 
xAxisRotation: 2 
largeArc: 2 
sweep: 2 
clipMask: 2 
FILLRULE: 2 
url: 2 
array: 2 
scale: 2 
LAYER: 1 
amplitude: 1 
waveLenght: 1 
enable: 1 
azimuth: 1 
elevation: 1 
low: 1 
high: 1 
embedText: 1 
INTERPOLATE: 1 
ORIENTATION: 1 
method: 1 
page: 1 
server_name: 1 
LAYERMETHOD: 1 
ALPHACHANNELTYPE: 1 
delta_x: 1 
rigidity: 1 
METRICTYPE: 1 
storage: 1 
PIXEL: 1 
cluster_threshold: 1 
smooth_threshold: 1 
verbose: 1 
SPARSE_METHOD: 1 
DITHER: 1 
STORAGE: 1 
FUNCTION: 1 
factor: 1 
files: 1 
mode: 1 
modify: 1 
filenames: 1 
imageFormat: 1 
adjoin: 1 
label: 1 
quality: 1 
COMPRESSION: 1 
tileGeometry: 1 
thumbnailGeometry: 1 
MONTAGEMODE: 1 
frame: 1 
appendRawOutput: 1 
levels: 1 
raise: 1 
FILTER: 1 
filter: 1 
channel: 1 
delay: 1 
callback: 1 
scene: 1 
ticksPerSecond: 1 
RESOLUTION: 1 
xShear: 1 
yShear: 1 
multiline: 1 
NOISE: 1 
frames: 1 
orig_width: 1 
orig_height: 1 
desired_width: 1 
desired_height: 1 
colorize_color: 1 
kernel: 1 
displace: 1 
constant: 1 
innerBevel: 1 
outerBevel: 1 
expression: 1 
complement: 1 
PREVIEW: 1 
DISPOSETYPE: 1 
RENDERINGINTENT: 1 
VIRTUALPIXELMETHOD: 1 
midpoint: 1 
tint_color: 1 
amount: 1 
background_color: 1 
pseudoString: 1 
compression: 1 
compressionquality: 1 
RESOURCETYPE: 1 
limit: 1 
factors: 1 
color_matrix: 1 
type: 1 
morphologyMethod: 1 
strength: 1 
kerning: 1 
x_resolution: 1 
y_resolution: 1 
encoding: 1 
fontfamily: 1 
STYLE: 1 
weight: 1 
start: 1 
end: 1 
sd: 1 
ed: 1 
METHOD: 1 
coordinates: 1 
STRETCH: 1 
ALIGN: 1 
DECORATION: 1 
affineMatrix: 1 
COMPOSE: 1 
PAINTMETHOD: 1 
pattern_id: 1 
PATHUNITS: 1 
fillOpacity: 1 
LINECAP: 1 
LINEJOIN: 1 
miterLimit: 1 
strokeOpacity: 1 
xml: 1 
dashArray: 1 
density: 1 
direction: 1 
luminosity: 1 
color_value: 1 
normalized: 1 
colorCount: 1 
srcPixel: 1 
kerneltype: 1 
paramstring: 1 
normalize_flag: 1

**Comment by Danack** [comment]
btw the code for generating those is below. I'll add it to the  param_names_cleanup branch when the current PR I'm working on is finished.

```
<?php

declare(strict_types = 1);


$classes = [
    'Imagick',
    'ImagickDraw',
    'ImagickPixel',
    'ImagickKernel'
];


foreach ($classes as $class) {
    $nameCounts = [];


    echo "class = $class \n";

    $classReflection = new ReflectionClass($class);
    $classMethods = $classReflection->getMethods();

    foreach ($classMethods as $imagickMethod) {
        $parameters = $imagickMethod->getParameters();
        foreach ($parameters as $parameter) {
            $name = $parameter->getName();
            $nameCounts[$name] = ($nameCounts[$name] ?? 0) + 1;
        }
    }


    arsort($nameCounts);

    foreach ($nameCounts as $name => $count) {
        echo "$name: $count \n";
    }

    echo "\n\n";

}

```

**Comment by mkoppanen** [comment]
I think historically the all caps names were to indicate constants. I wonder if it would make sense to keep those not to confuse with normal ints? Or maybe something like Hungarian notation?

**Comment by Danack** [comment]
I have a surprisingly strong opinion that parameter names. I find it much easier to have the same name for parameters across all languages that might be used for a site i.e. frontend, backend and DB, so that programmers don't need to map 'channel' to 'CHANNEL'.

btw the names come from the stub files like: https://github.com/Imagick/imagick/blob/param_names_cleanup/Imagick.stub.php and need to be regenerated by running the script: https://github.com/Imagick/imagick/blob/c850f77f8519fa981e072e458124ba11fc894ad2/util/fixup_arginfo.php


The one's that really need checking are:

## Class names instead of specific names

e.g. where Imagick, ImagickDraw, ImagickKernel some of those are appropriate, but some of them might be better as draw_settings

## differentiate quantum names

The parameters that take values 0 to Imagick::getQuantum(), should be clearly different from parameters than take 0-1 or 0-255 imo.


## array

that should be better.


## all of the x, y and x1, x2 ones

I think some of those should be named like top_left_x or start_x, and bottom_right_x etc.

**Comment by Danack** [comment]
Imagick
ImagickDraw
~~ImagickKernel~~
ImagickPixelIterator
ImagickPixel



### Summary of what needs to be reviewed

* Class names instead of specific names - e.g. where Imagick, ImagickDraw, ImagickKernel some of those are appropriate, but some of them might be better as draw_settings

* differentiate quantum names  - The parameters that take values 0 to Imagick::getQuantum(), should be clearly different from parameters than take 0-1 or 0-255 imo. Think I'll append 'quantum' to indicate the difference.

* array - that should be better.
* all of the x, y and x1, x2 ones - I think some of those should be named like top_left_x or start_x, and bottom_right_x etc.

### Summary of horribly wrong ones that are not obvious what to call them

* ImagickPixel::isPixelSimilarQuantum - $fuzz_quantum_range_scaled_by_square_root_of_three is accurate, but very bad.

**Comment by Danack** [comment]
>  I wonder if it would make sense to keep those not to confuse with normal ints?

@mkoppanen Now that PHP has enums, when support for PHP < 8.1 is dropped, Imagick will be able to put all the constants into their own separate types, and then be able to define the methods like:

```
    public function setFontStyle(Style $style): bool {}
```

So, maybe around 2027.

**Comment by Danack** [comment]
Mental note, need to double-check $columns vs $cols everywhere...

**Comment by Danack** [comment]
This was done in the 3.5.0 release.
