### ISSUE TITLE
Uploading a .gif file of 15mb size fails

### ISSUE THREAD

**Issue by pamamolf** [Imagick/imagick#349]
Hello

Using php 7.4.10 and ImageMagick latest when i upload a .gif file of 15mb size it fails and returns an error 502.

Using GD it works without any issues and in less than 10 secs.

Thank you

**Comment by Danack** [comment]
It looks like something isn't working on your server.

But only someone with access to your server could figure out why. Please see how you could get more info than just 502. 

[How can I get useful error messages in PHP?](https://stackoverflow.com/questions/845021/how-can-i-get-useful-error-messages-in-php)
