### ISSUE TITLE
Compiling Imagick failed

### ISSUE THREAD

**Issue by Jack7244** [Imagick/imagick#352]
/soft/php/imagick-3.4.4RC2/imagick_file.c:22:
/soft/php/imagick-3.4.4RC2/php_imagick_file.h:61:108: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 d_bool php_imagick_file_init(struct php_imagick_file_t *file, const char *filename, size_t filename_len TSRMLS_DC);
                                                                                                         ^~~~~~~~~

/soft/php/imagick-3.4.4RC2/php_imagick_file.h:65:54: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 int php_imagick_safe_mode_check(const char *filename TSRMLS_DC);
                                                      ^~~~~~~~~
In file included from /soft/php/imagick-3.4.4RC2/imagick_file.c:22:
/soft/php/imagick-3.4.4RC2/php_imagick_file.h:68:134: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 magick_read_file(php_imagick_object *intern, struct php_imagick_file_t *file, ImagickOperationType type TSRMLS_DC);
                                                                                                         ^~~~~~~~~

/soft/php/imagick-3.4.4RC2/php_imagick_file.h:71:153: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 hp_imagick_object *intern, struct php_imagick_file_t *file, ImagickOperationType type, zend_bool adjoin TSRMLS_DC);
                                                                                                         ^~~~~~~~~

/soft/php/imagick-3.4.4RC2/php_imagick_file.h:74:112: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 ol php_imagick_stream_handler(php_imagick_object *intern, php_stream *stream, ImagickOperationType type TSRMLS_DC);
                                                                                                         ^~~~~~~~~

/soft/php/imagick-3.4.4RC2/imagick_file.c:81:51: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 zend_bool php_imagick_is_url(const char *filename TSRMLS_DC)
                                                   ^~~~~~~~~
/soft/php/imagick-3.4.4RC2/imagick_file.c:91:108: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 nd_bool php_imagick_file_init(struct php_imagick_file_t *file, const char *filename, size_t filename_len TSRMLS_DC)
                                                                                                          ^~~~~~~~~

/soft/php/imagick-3.4.4RC2/imagick_file.c:160:133: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 using_imagemagick(php_imagick_object *intern, struct php_imagick_file_t *file, ImagickOperationType type TSRMLS_DC)
                                                                                                          ^~~~~~~~~

/soft/php/imagick-3.4.4RC2/imagick_file.c:201:133: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 using_php_streams(php_imagick_object *intern, struct php_imagick_file_t *file, ImagickOperationType type TSRMLS_DC)
                                                                                                          ^~~~~~~~~

/soft/php/imagick-3.4.4RC2/imagick_file.c:255:54: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 int php_imagick_safe_mode_check(const char *filename TSRMLS_DC)
                                                      ^~~~~~~~~
/soft/php/imagick-3.4.4RC2/imagick_file.c:269:134: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 imagick_read_file(php_imagick_object *intern, struct php_imagick_file_t *file, ImagickOperationType type TSRMLS_DC)
                                                                                                          ^~~~~~~~~

/soft/php/imagick-3.4.4RC2/imagick_file.c:288:153: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 php_imagick_object *intern, struct php_imagick_file_t *file, ImagickOperationType type, zend_bool adjoin TSRMLS_DC)
                                                                                                          ^~~~~~~~~

/soft/php/imagick-3.4.4RC2/imagick_file.c:313:112: error: expected ‘;’, ‘,’ or ‘)’ before ‘TSRMLS_DC’
 ool php_imagick_stream_handler(php_imagick_object *intern, php_stream *stream, ImagickOperationType type TSRMLS_DC)
                                                                                                          ^~~~~~~~~

make: *** [Makefile:209: imagick_file.lo] Error 1

**Comment by Danack** [comment]
I'm guessing you were trying to compile with PHP 8, which wasn't possible. If that's not the case feel free to give more info about what environment you were trying to compile in.

**Comment by Jack7244** [comment]
The system is Centos version 8.2, 2004

**Comment by Danack** [comment]
Sorry - I meant, what version of PHP are you trying to compile against?
