### ISSUE TITLE
test 14 suddenly failing

### ISSUE THREAD

**Issue by Danack** [Imagick/imagick#362]
```
FAIL Imagick::setResourceLimit test [tests/014-setresourcelimit.phpt]

Error testing 4, value returned 536870912 is not 10737418240 
Error testing 5, value returned 268435456 is not 10737418240 
Error testing 9, value returned 16000 is not 1073741824 
Error testing 10, value returned 16000 is not 1073741824 
```

This looks like an internal change to ImageMagick, where they put some sensible max values in the policy file, maybe?

@mkoppanen If you have the time/inclination, can you check where these are coming from? We'll need to document where they live for users. 

Also updating the test to not fail would be good. Currently it does attempt to set absurd limits on the resources, which ImageMagick is probably correct in not respecting.

**Comment by darki73** [comment]
Given the fact that the change implemented is probably not yet covered by tests, here is a `super/omega/please_dont_use_in_production` method to **_"fix"_** the aforementioned problem
```
RUN git clone --branch master https://github.com/Imagick/imagick /tmp/imagick \
    && cd /tmp/imagick \
    && rm tests/014-setresourcelimit.phpt \
    && sed -n '/014-setresourcelimit.phpt/d' package.xml \
    && phpize  \
    && ./configure  \
    && make -j$(nproc) \
    && make install \
    && make test \
    && echo 'extension=imagick.so' > /usr/local/etc/php/conf.d/imagick.ini \
    && rm -rf /tmp/imagick
```

**Comment by Danack** [comment]
The test is working now....this was probably a package change somewhere along the lines, where some resource limit got changed on the system it was being used on.

But the test appears to be working now, so hard to investigate it.
