### ISSUE TITLE
setImageClipMask() deprecated without alternative

### ISSUE THREAD

**Issue by ragcsalo** [Imagick/imagick#370]
One of my projects is highly dependent on the setImageClipMask()  function, which is missing from Imagick v7.0 for PHP. Now I'm devastated... can't find a decent PHP image handling library that would support image masking (basically I'd like to blur a part of an image, based on a PNG mask image). Any ideas how could I solve this problem?

**Comment by Danack** [comment]
It looks like the underlying function has changed from setImageClipMask to [SetImageMask](https://imagemagick.org/api/magick-image.php#MagickSetImageMask) which hasn't been added to the Imagick API yet.

It's been on my big list of things to do, to go through all the changes from ImageMagick 6->7 and figure out:

* are the replaced functions compatible, or can they be made compatible.
* writing documentation on the changes needed.
* what are the new features that weren't present in IM6.

**Comment by ragcsalo** [comment]
Thanks for the info. :-) So it means we can't use the setImageMask() function with the PHP API yet? Is there any workaround, or I'll have to look for an Imagick alternative that can use masks for certain operations?

**Comment by Danack** [comment]
> So it means we can't use the setImageMask() function with the PHP API yet?

That is correct.

Good news, it's in the next release, and read and write masks appear to work. Though composite masks appears to have 'surprising' behaviour:

![Screen Shot 2021-06-02 at 19 26 06](https://user-images.githubusercontent.com/1505719/120536347-edcfba00-c3db-11eb-89ab-9042f261fc86.png)

**Comment by myrecs** [comment]
also tried to find the solution. 7 version is ugly( it is not the single problem, this version is too much cut and corrupted!

**Comment by Danack** [comment]
The problem with setImageMask in ImageMagick has allegedly been fixed. I'm in the process of making an example for it for phpimagick.com, but there is example code in the test: https://github.com/Imagick/imagick/blob/a4b15a946ece4bee8b8023b3272fc3fd2bf3bc04/tests/289_Imagick_setImageMask_basic.phpt

@myrecs the version of ImageMagick that is was fixed in was on the [12th June 2021](https://github.com/ImageMagick/ImageMagick/issues/3779). You may need to upgrade to a version after that. And then open a separate issue if you're still seeing problems with it.

**Comment by myrecs** [comment]
i'll check it, thanks.
what about  absent constant ALPHACHANNEL_RESET? i dont remember the details but it was unable for me to make proper mask without this construction:
.....
$im->cropImage($w,$h,$x,$y);
$im->setImagePage(0, 0, 0, 0);
$im->setImageAlphaChannel(Imagick::ALPHACHANNEL_RESET); <----!!!
$im->setImageAlphaChannel(Imagick::ALPHACHANNEL_ACTIVATE);
...
i admit that may be there is some other solution and may be it could be made in more elegant way, but unfortunately i could not find it.

**Comment by Danack** [comment]
@myrecs 
> And then open a separate issue if you're still seeing problems with it.

@ragcsalo I believe the upstream issue is fixed. There is a crappy example of the usage here https://github.com/Imagick/ImagickDemos/blob/9c82fdb35c3ff910c5983f2050c5d4c6e8b7c497/src/ImagickDemo/Imagick/functions.php#L2050-L2110

I'm in the process of upgrading the phpimagick.com site to PHP8 and ImageMagick 7 which is taking a while, so can't deploy the example to the live site yet.
