### ISSUE TITLE
Bug or Incompatibility by default (error/blob.c/OpenBlob/3496)

### ISSUE THREAD

**Issue by ATOPBIO** [Imagick/imagick#374]
Hello, when trying to convert a PDF to JPG, but I am encountering the error:

**error/blob.c/OpenBlob/3496**

I am using a Wordpress on apache, linux server managed by CPanel.

Could you please advise how I should solve this?
I also submitted this as question on [stackoverflow](https://stackoverflow.com/questions/65657834/converting-pdf-to-image-in-php-with-imagick-cpanel-apache-wordpress-linux).

**Comment by Danack** [comment]
Sorry, I have no idea.

For the record, I strongly recommend downloading files first, rather than trying to open through HTTP inside Imagick.
