### ISSUE TITLE
PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1654 but version 1650 is loaded

### ISSUE THREAD

**Issue by lgdelai** [Imagick/imagick#376]
Hello everyone.

In my hosting at **Hostgator** I am receiving this error without stopping in the "**error_log**" file.

The file "**error_log**" containing this message appears on several random pages.

In addition, I receive the following message **every hour**, in the standard cpanel email:
**Title:**
**Cron <delaio86 @ srv100> / usr / bin / php -f /home2/delaio86/public_html/utilidadeninja.com/site/wp-cron.php> / dev / null**

**Content:**
```
PHP Warning: Module 'imagick' already loaded in Unknown on line 0
PHP Warning: Version warning: Imagick was compiled against Image Magick version 1654 but version 1650 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
```

In contact with the Hosting, I was informed that this is an incompatibility of Imagick with versions **73 and 74 of PHP**.

The attendant then said that he could not do anything because it is a shared hosting and suggested that I use an outdated version "**72**" of php.

**I said that I would not use an outdated version, for obvious reasons.**

I would like your help to try to stop generating these messages in the log for all my folders without having to outdate my PHP.

I often have to look for the files and delete them one by one, as they never stop growing.

I already tried to insert a **.user.ini** file containing the line:
`imagick.skip_version_check = true`
And a **php.ini** file with the line:
`extension = imagick.so`

Both, in the root folder of the hosting, the errors continue to appear randomly.

Thanks in advance to anyone who can help.

**Comment by Oldiesmann** [comment]
The error message is clear - The Imagick extension was compiled against a newer version of ImageMagick than what's on the server. It has nothing to do with the PHP version. The skip_version_check option won't work in a .user.ini file - only the main PHP configuration file. Ask the host to change it for you.

**Comment by Danack** [comment]
Hi @lgdelai 

This sounds like a problem for your hosting company to address. If they're providing different versions of libraries, they should be making sure you get the correct versions...not subtly different versions.

I'd recommend looking at using a dedicated VPS e.g. from https://www.vultr.com/products/cloud-compute/ or Digital Ocean are also nice.

**Comment by lgdelai** [comment]
Hei @Danack  and @Oldiesmann 

I found a solution how actually work for me:

I will share here, maybe can help others:

I need to create a **php.ini** file on all folder where this error apears,
Inside of the **php.ini** file i put the below code:
`imagick.skip_version_check=true`

This works fine to me!

@Danack  The problem I have with dedicated servers is that I believe that I will have to make much more complex configurations that come ready-made, not shared.
Besides that not included already comes with cPanel installed, and I have a lot of affinity with cPanel.
That's it? or do I get protection and usability comparable to the shared server in a VPS?

**Thanks everyone for the help.**
