### ISSUE TITLE
request php8.0 for windows

### ISSUE THREAD

**Issue by haohetao** [Imagick/imagick#377]

**Comment by DeyV** [comment]
Not official but working dll's are avalliable on https://github.com/mentax/Imagick_for_php8

**Comment by LucaDev** [comment]
Take a look at: https://github.com/Imagick/imagick/issues/358

There is no official release planned right now.

**Comment by ve3** [comment]
Installed from that link but not working. Sadly.

**Comment by Danack** [comment]
For the record, I don't recommend downloading binaries from random people. But I do recommend funding open source development.

Closing as the other thread is long enough...
