### ISSUE TITLE
Can I install Imagick 7.4 on PHP server 8.0.2?

### ISSUE THREAD

**Issue by harel555** [Imagick/imagick#381]
HI
Can I install Imagick 7.4 Thread Safe (TS) x64 on PHP server 8.0.2?
I have XAMPP for Windows 8.0.2

the link is:
https://pecl.php.net/package/imagick/3.4.4/windows

Couldn't find later version.
I am not a programer.
I need it to work with pictures in Word Press

Thanks Harel

**Comment by LucaDev** [comment]
For now, the easiest way is to downgrade to PHP<8.0.0

Take a look at: https://github.com/Imagick/imagick/issues/358#issuecomment-789271738

**Comment by harel555** [comment]
Thanl you

**Comment by sojimaxi** [comment]
@harel555 Look at https://github.com/mentax/Imagick_for_php8
