### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by orep1x** [Imagick/imagick#384]
$im->writeImage("test.png");

Uncaught ImagickException: no encode delegate for this image format `' @ error/constitute.c/WriteImage/1239

**Comment by Danack** [comment]
Imagick uses ImageMagick underneath to do the image processing. 

When it is compiled, ImageMagick will look for specific libraries to handle specific file formats. For PNG images, on Linux systems it will look for `libpng-dev`

When configure is run for ImageMagick
```
./configure --with-quantum-depth=16            --with-magick-plus-plus=no            --without-perl            --disable-static            --disable-docs
```

Somewhere in the output will be the result of it looking for the libpng library:

```
configure:31786: checking for libpng >= 1.0.0
configure:31793: $PKG_CONFIG --exists --print-errors "libpng >= 1.0.0"
configure:31796: $? = 0
configure:31810: $PKG_CONFIG --exists --print-errors "libpng >= 1.0.0"
configure:31813: $? = 0
configure:31851: result: yes
```
