### ISSUE TITLE
Why php_imagickpixel_get_class_entry() returns php_imagickdraw_sc_entry?

### ISSUE THREAD

**Issue by pdombrovsky** [Imagick/imagick#387]
Hello!
Why php_imagickpixel_get_class_entry() returns php_imagickdraw_sc_entry when it should return php_imagickpixel_sc_entry?
See lines 88-91 in imagick.c.
![question](https://user-images.githubusercontent.com/81902477/113503879-43532c00-953d-11eb-800d-ee3c5fc17daf.jpg)

**Comment by Danack** [comment]
Thanks. Yep that looks like a typo.

Wouldn't cause a problem internally, just for people calling that code from another extension.....which probably no-one does.

**Comment by pdombrovsky** [comment]
Exactly. I am developing my own extension. In one of the methods, it would be more convenient for me to call php_imagickpixel_get_class_entry () rather than passing the components (r, g, b, a) separately.
