### ISSUE TITLE
Imagick suddenly stopped working

### ISSUE THREAD

**Issue by AeonDeveloper** [Imagick/imagick#388]
$image = new Imagick($dith2_jpg);  

this ^^^^^ above line of code doesn't work and the script stops processing, no lines  under this one run.  interesting,  even putting am

echo 'blah';

 won't compile in the browser.   No idea what is happening, I did update my test server to php 8.0 recently.   i have some stuff in imageMagick running on the command line that didn't break.

I hope this is the right place to list the issue.

thank you for your hard work on this awesome tool.....

**Comment by Danack** [comment]
Sorry, I won't be able to fix it directly, as whatever is happening is likely to be specific to your server. I'd suggest:

1. looking at this answer on StackOverflow on how to get error output: https://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display

2. Try running it from the command line as that might avoid some file permission issues. If that "makes the problem go away", it's likely to be a file permission issue. If it doesn't try 3.

3. Run it from the command line through the strace linux utility e.g. `strace php debug.php` which might give some info.

**Comment by Danack** [comment]
Feel free to update if you find some info you can share, but otherwise there's nothing I'd be able to do.

btw, I do recommend using ansible, vagrant, docker or similar container technologies to be able to rebuild servers from scratch, as yeah, sometimes 'stuff happens' when upgrading.
