### ISSUE TITLE
get ride of annotation in pdf file using imagick

### ISSUE THREAD

**Issue by saadzizi** [Imagick/imagick#389]
I translate pdf to jpg using imagick;

but it return area with black color because of annotations existing in pdf file, annotaions apear when I hover pictures in pdf file

```
$img = new Imagick('./pige.pdf[1]');
$img->setImageBackgroundColor('white');

$img = $img->flattenImages();

$img->setImageFormat('jpg');
$img->writeImage('image.jpg');
```

**Comment by Danack** [comment]
I don't know if it's possible.

Can you upload an example PDF somewhere so I can have a go?

**Comment by saadzizi** [comment]
this the pdf file :: https://drive.google.com/file/d/1qmaKBA5vd-2_I4WlpZs8oInKGONNOBRb/view
this the result after translating pdf to jpg:: https://drive.google.com/file/d/1sG7ONW3IhtUugD8DEaf9B5Om06Em_SiH/view?usp=sharing

**Comment by Danack** [comment]
So. That has even worse output on my machine.

This appears to be a bug in the ghostscript version that is installed with ImageMagick by default. Ghostscript is the program that actually does the conversion from pdf to a rendered bitmap.

I tried the latest version of Ghostscript that I downloaded from: https://www.ghostscript.com/download/gsdnld.html

Converting your PDF with the command line:

```
gs-9540-linux-x86_64 -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' '-sOutputFile=/var/app/bugs/bug389/gs_output.png' '-f/var/app/bugs/bug389/pige.pdf'
```
and it appears to work okay.

I think if you:

* find where ghost script is on your machine by running `which gs`
* then just replace that file (after backing the original one up somewhere) with the one downloaded from https://www.ghostscript.com/download/gsdnld.html that may make your problem go away.

**Comment by saadzizi** [comment]
It works perfectly thank you @Danack

**Comment by Danack** [comment]
Hi @saadzizi glad I could help. If possible, please could you do me (actually this project) a big favour.

Could you ask whoever makes your PDFs to create a PDF using this image: https://github.com/Imagick/imagick/blob/test_image/tests/images/Robin.jpg to make a one page PDF similar to the one that was showing the problem and contribute it to the project?

This kind of problem is something that could do we having distributing a test for, but for that I'd need a PDF that doesn't belong other people's copyrighted images.

**Comment by saadzizi** [comment]
so this pdf I scraped it from dealer website [auchan](https://catalogue.auchan.fr/ ), sometimes their pdf produce this bug.
Unfortunately I didn't succeed to reproduce this bug by my self, I will gave it an other try.

**Comment by Danack** [comment]
Ok thanks for trying. I'll open another issue asking for help with a reproducible PDF that isn't copyright encumbered.
