### ISSUE TITLE
Help wanted: improve github actions

### ISSUE THREAD

**Issue by Danack** [Imagick/imagick#396]
Thanks to @Nielsvanpach the project now has working github actions, they could do with some improvement.

One problem is that although using shivammathur/setup-php action is convenient, it means that any problem with the CI can't be easily reproduced locally. Also, the libraries used by ImageMagick that ship on Ubuntu have shown more problems over the years than I've experienced on Debian.

Requirements:

* use containers based on debian or debian slim with the docker files stored in the /docker directory.
* compile php src from scratch. Although there are some external repos that provide various versions of PHP, these are either explicitly not intended to be maintained for as long as this project would need them, or they require a paid service.
* cache the built version of PHP, so that builds don't take ages.
* cache the built version of ImageMagick, so that builds don't take ages.

I'd be fine with having one docker file per version of PHP. Duplication is definitely cheaper than trying to be clever for CI tasks. But having one dockerfile per combination of PHP version and ImageMagick would be too many.

An appropriate configure script for PHP would be:

```
./configure \
  --without-pear \
  --without-sqlite3 \
  --without-pdo-sqlite \
  --with-openssl \
  --enable-mbstring \
  --with-curl
```
And the basic libraries needed in the container are the same as the ['developing'](https://github.com/Imagick/imagick/blob/master/docker/developing/Dockerfile) container I use.

**Comment by seebeen** [comment]
Hey, I just read the issue. When do you want the actions to run, and can you clarify on the usage of pre-built ImageMagick?

**Comment by Danack** [comment]
The actions are setup to run at the correct time - which is on push.

For the whole matrix of combinations of PHP and ImageMagick versions, ImageMagick is currently being downloaded, compiled and installed.

When the tests were running on Travis, ImageMagick was compiled into [im_dir=${HOME}/im/imagemagick-${version}](https://github.com/Imagick/imagick/blob/35741750aa1cda2b7ac354bfa6128fa037e9cf32/imagemagick_dependency.sh#L10-L28) and that directory was tested to exist and also cached by Travis.

Which meant the majority of the time ImageMagick didn't need to be downloaded, it just needed to be installed (rather than a full compilation), which was a lot quicker. Currently the full tests take almost an hour to run, and downloading ImageMagick and compiling it takes about 75% of that time, and also heats up the planet.

Github actions supports caching of build steps, but it works in quite a different way to Travis, so I don't know how it would work, but it is possible.

**Comment by Danack** [comment]
This looks like the thing to use:

https://levelup.gitconnected.com/github-actions-how-to-share-data-between-jobs-fc1547defc3e

```
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-


```

**Comment by Danack** [comment]
More jobs " -j##"

**Comment by Danack** [comment]
The caching is actually done.
