### ISSUE TITLE
Help wanted: nixos font config

### ISSUE THREAD

**Issue by Danack** [Imagick/imagick#398]
@stephank kindly added a docker container for nixos, and the extension builds, but it seems quite a few tests that use fonts fail due to fontconfig giving an error message:

```
Fontconfig error: Cannot load default config file
```

I had a quick look at trying to find how to avoid that, and [found this](https://discourse.nixos.org/t/fonts-in-nix-installed-packages-on-a-non-nixos-system/5871):

> I use fish, so you’ll have to adapt this to whichever shell you use, but this works for me: set --global --export FONTCONFIG_FILE ${pkgs.fontconfig.out}/etc/fonts/fonts.conf EDIT: (add that to your home-manager’d shell config)

But that gives:

> bash: ${pkgs.fontconfig.out}/etc/fonts/fonts.conf: bad substitution

Anyone know what the proper fix is to prevent the error message being shown?

**Comment by stephank** [comment]
Ah, they're talking about a substitution in Nix, not in the shell. We can do that in `shell.nix`, I'll make a PR. 👍

**Comment by Danack** [comment]
Thanks for that.

At first I thought it wasn't working, then I realised that I'd been caught by the way that docker doesn't seem to know to rebuild images when one of the files that are copied internally is changed.

I normally try and avoid copying files if at all possible with docker as that type of thing keeps catching me up. 

Is there any strong reason against leaving the shell.nix where it is and running it with:
https://github.com/Imagick/imagick/commit/d15a015b55cb5f644916c6fa6aed4995506a631c ?

I know it's probably not an appropriate thing to do for a deployment build...but this is more of a dev container.

**Comment by stephank** [comment]
Ah, good point! And nope, that's perfectly fine. 👍
