### ISSUE TITLE
Moving a working Debian 10 Wordpress to CentOS 8 with remi php8.? imagick extension does not load

### ISSUE THREAD

**Issue by gguldens56** [Imagick/imagick#401]
Running Wordpress and Warp-Imagick plugin on CentOS 8.3 and php8 from remi.  I always get a message "required PHP extension: "PHP Imagick" is missing.  I have verified everything in /etc/php.ini and in the /etc/php.d extensions files located there.  Still nothing I have done has caused the warp-Imagick plugin to recognize the Imagick PHP extension.  Any thoughts on this would be appreciated.  Thanks,  Greg Guldenschuh

**Comment by Danack** [comment]
How did you install Imagick? It won't be there by default with just installing PHP.


You might be able to find some info by showing the output of `phpinfo();`

**Comment by Danack** [comment]
Closing as I think you just need to install imagick with something `yum install php-imagick` or whatever the appropriate centos incantation is.
