### ISSUE TITLE
Imagick not loading on php8.  New information

### ISSUE THREAD

**Issue by gguldens56** [Imagick/imagick#408]
running php-i I found the following:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php-zts/modules/imagick.so' (tried: /usr/lib64/php-zts/modules/imagick.so (/usr/lib64/php-zts/modules/imagick.so: undefined symbol: core_globals_offset), /usr/lib64/php/modules///usr/lib64/php-zts/modules/imagick.so.so (/usr/lib64/php/modules///usr/lib64/php-zts/modules/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

It seems that imagick,so has an undefined symbol of core_globals_offset.  Any thoughts on this?

**Comment by Danack** [comment]
How did you install Imagick?

Due to a number of reasons, including being preoccupied with thinking about the morality of open source, I haven't actually done a release of Imagick for PHP 8 yet, so it's not too suprising it didn't work.

**Comment by Danack** [comment]
Ok. Feel free to reopen if you can provide info, but this sounds like you've copied files around that aren't compatible with each other.
