### ISSUE TITLE
After server restart, imagick not available to PHP7.4

### ISSUE THREAD

**Issue by NFGman** [Imagick/imagick#415]
After a server (ubuntu server 20.04) reboot this morning, imagick is no longer available to my PHP7.4 installation. It worked fine yesterday, it's been working fine for years. I use it across a dozen websites and it's never been anything less than painless and effective. And now, 'class 'imagick' not found' is all I can get.

I've removed and purged and installed php-imagick to no avail. PHP doesn't throw any errors as if it fails to load the module, it doesn't seem to even try. PHP's extension_dir is 2019xxx and imagick.so installed to 2020xxx, but copying this file to the 2019 dir has no effect.

phpinfo doesn't list imagick, php -m doesn't list it. There are no errors in php -i. running 'convert' from terminal works fine. It's installed, but PHP can't see or use it.

I'm at my wits end, and two hours of searching for answers has gotten me nowhere. I would appreciate any help.

(My apologies if this isn't an appropriate place to ask - please direct me elsewhere if appropriate)

**Comment by Danack** [comment]
> but copying this file to the 2019 dir has no effect.

fyi you can't copy binary files around like that. When C code is compiled, it's compiled against a specific set of symbols and libraries, which includes doing things like "figuring out how big some data is in bytes, and then writing exactly that size of data in bytes". 

> PHP's extension_dir is 2019xxx and imagick.so installed to 2020xxx

That sounds like whatever you used to install imagick installed the version for PHP 8.

If you do `apt search imagick` there might be a version that is explicitly named php74-imagick, or similar.

I have no idea what happened btw....but I guess maybe your system did some sort of update during the reboot due to it being confused about what packages you have installed....but hard to say.

**Comment by Danack** [comment]
If you can't figure it out, please can you say:

* exactly what command you used to install PHP and what command you used to install Imagick.
* which RPM repos you are using? e.g. stock ubuntu ones, or Remi or sury.org or similar.

**Comment by NFGman** [comment]
I don't recall what commands I used to install it originally, that was 2+ years ago and, well, my memory's not _that_ good.  ;)

I tried to install **php7.4-imagick**, but 

```
Package php7.4-imagick is a virtual package provided by:
  php-imagick 3.4.4-4 [Not candidate version]
```

The only way to install imagick is to first install **imagemagick**, then **php-imagick** The specific version I'm getting, when I install, is:

`installed php-imagick:amd64 3.4.4+php8.0+3.4.4-7+ubuntu20.04.1+deb.sury.org+1`

Now, I read '+php8.0' to mean _'as well as PHP8.0'_ but perhaps that means _only_ PHP8?  But since there is no 7.4, apparently, I don't have any idea where to go from here.

----

For repos, just the standard ubuntu, and ondrej for PHP.

**Comment by Danack** [comment]
Well, if you can't remember maybe `apt show php` would show you what you have. 

I see you've found the deb sury repo. That might be a more appropriate place to get help. Be sure to sponsor Ondřej though.

**Comment by NFGman** [comment]
Well, 'apt show php' says I have PHP 8, but I never installed 8, it's specifically disallowed in apt preferences, and 'php -version' shows 7.4.13.  I can't _remove_ PHP 8 because it's not installed.  One more clue for the pile...

Thank you for the help.  I've been bounced around a half dozen forums already and so far the feeling I get is, as usual, no one else in the history of ever has had this problem (And maybe ask someone else?).  (This is a sincere thanks, if it feels snarky it's not supposed to).

**Comment by NFGman** [comment]
Well, it's fixed, sort of.  For reasons I can't fathom I had to allow PHP 8 to be installed before PHP7.4 could be installed before php-imagick would support PHP7.4...

I still don't know why it works but it does.  Thank you for the help.
