### ISSUE TITLE
Problems with DistortImage when using bestfit = true

### ISSUE THREAD

**Issue by MarliesMaalderink** [Imagick/imagick#419]
Using ImageMagick::DistortImage with constant Imagick::DISTORTION_PERSPECTIVE in version 3.4.4 I am encountering the following problem.

```
$leftFace->distortImage(Imagick::DISTORTION_PERSPECTIVE, $perspectiveGoal, true);
```

Where $leftFace is 1500x1500 pixels and $perspectiveGoal:
```
array:16 [
  0 => 0
  1 => 0
  2 => 241
  3 => 106
  4 => 0
  5 => 1500
  6 => 241
  7 => 1412
  8 => 1500
  9 => 0
  10 => 325
  11 => 95
  12 => 1500
  13 => 1500
  14 => 325
  15 => 1428
]
```

comes out with a width of 86 ( 325 - 241 = 86) and a height of 1335  (1428-95 = 1333)

Theoretically this is a height 2 pixels less then expected, but it's the same result I get when setting the $bestfit parameter to false. (which is the result I would expect and also the result I get when using Image Magick directly on command line, so that's ok.)

Now here's the problem, when doing:

```
$rightFace->distortImage(Imagick::DISTORTION_PERSPECTIVE, $perspectiveGoal, true);
```

Where $rightFace is 1500x1500 pixels and with $perspectiveGoal:
```
array:16 [
  0 => 0
  1 => 0
  2 => 325
  3 => 95
  4 => 0
  5 => 1500
  6 => 325
  7 => 1428
  8 => 1500
  9 => 0
  10 => 1264
  11 => 178
  12 => 1500
  13 => 1500
  14 => 1264
  15 => 1328
]
```

returns an image with a width of 926 and a height of 1324, which is less then the expected size of 941 (1264−325 = 939) x 1335 (1428−95 = 1333) that distortImage returns when using $bestfit = false and the size Image Magick returns on the commandLine. (Again there is a difference of 2 pixels that seems to happen all the time and that's fine by me.)

I do not understand why this second image keeps coming out with 13 pixels less width and 9 pixels less height then expected. I triple checked all values that go into the function so I am pretty sure I didn't miss anything.

I could, as a last resort, set $bestfit to false, but it makes the code a lot slower for some reason and I am processing a lot of images.

Is there a reason why sometimes these distorts are behaving unexpectedly when using $bestfit=true? Or am I overlooking something here? Any help would be appreciated!

**Comment by Danack** [comment]
Please can you reformat this as runnable code, to save me that time? 

http://sscce.org/

Including writing the file out.


An appropriate test image can be created with:

```
$imagick = new Imagick();
$imagick->newPseudoImage(1000, 1200, "magick:logo");
```

Or whatever the appropriate size is.

**Comment by Danack** [comment]
Hi, 

I have far too many things to work on so going to close this for now. If you want to reopen the issue with a working reproduce case, go for it.

**Comment by MarliesMaalderink** [comment]
Hi,

I am very sorry that it took me a while, it turned out that the problem was a combination of 3 functions rather then an isolated issue in the distortImage function, so it took me a while to find the exact combination. 

It seems that the combination of crop/virtualPixelMethod along with a distort causes it. 

```
        $imagick = new Imagick();
        $imagick->newPseudoImage(1500, 1500, "pattern:checkerboard");
        $imagick->setImageFormat("png");

        $imagick->cropImage(1000, 1500, 500, 0);
        $imagick->setimagebackgroundcolor('none');
        $imagick->setImageVirtualPixelMethod(Imagick::VIRTUALPIXELMETHOD_TRANSPARENT);

        $coordinates =  [0,0,412,104,0,1500,412,1436,1500,0,1123,178,1500,1500,1123,1352];

         $imagick->distortImage(Imagick::DISTORTION_PERSPECTIVE, $coordinates, true);
         
         // And then another run with bestfit=false rather then true:
         // $imagick->distortImage(Imagick::DISTORTION_PERSPECTIVE, $coordinates, false);
         $imagick->trimImage(0);
```

If you would then echo $imagick->getImageWidth() and $imagick->getImageHeight() you would se a rather large difference, it seems that the further the offset of the crop moves from the 0,0 coordinate, the bigger the difference in the distortion becomes.

I just used the trim here so I could easily compare the size, but without the trim the issue is still there, visible when laying the results on top of eachother.

Anyway, the result of an echo on width and height returns: 455 * 1276 for $bestfit = true and 495 * 1334 for $bestfit = false

**Comment by MarliesMaalderink** [comment]
I can't open this issue by the way, so I hope you notice this reply...

**Comment by Danack** [comment]
> I am very sorry that it took me a while,

A few days is not a long time....

I have absolutely no idea what the correct behaviour here is, but it appears at least that the behaviour between the command line and Imagick are consistent.

Some code without the trim:

```
<?php

$imagick = new Imagick();
$imagick->newPseudoImage(1500, 1500, "pattern:checkerboard");
$imagick->setImageFormat("png");
$imagick->cropImage(1000, 1500, 500, 0);
$imagick->writeImage(__DIR__ . "/source_image.png");

$settings = [
    'false' => false,
    'true' => true
];

foreach ($settings as $name => $value) {

    $imagick = new Imagick(__DIR__ . "/source_image.png");

    $imagick->setimagebackgroundcolor('red');
    $imagick->setImageVirtualPixelMethod(Imagick::VIRTUALPIXELMETHOD_TRANSPARENT);

// Each of these is a source co-ordinate pair, along with where it is meant to end
// up in the transformed image
    $coordinates = [
        0, 0, 412, 104,
        0, 1500, 412, 1436,
        1500, 0, 1123, 178,
        1500, 1500, 1123, 1352
    ];

    $imagick->distortImage(Imagick::DISTORTION_PERSPECTIVE, $coordinates, $value);
    //$imagick->trimImage(0);

    $imagick->setImageFormat('png');
    $imagick->writeImage(__DIR__ . "/php_output_bestfit_" . $name . ".png");
}

$command = <<< CMD
convert source_image.png  -matte    -virtual-pixel transparent \
    +distort Perspective '0,0,412,104  0,1500,412,1436  1500,0,1123,178  1500,1500,1123,1352' convert_output_bestfit_true.png
CMD;

exec($command);

$command = <<< CMD
convert source_image.png  -matte    -virtual-pixel transparent \
    -distort Perspective '0,0,412,104  0,1500,412,1436  1500,0,1123,178  1500,1500,1123,1352' convert_output_bestfit_false.png
CMD;

exec($command);

echo "fin\n";

```

 The command line versions are the exact same dimensions as the Imagick generated versions.

Can you clarify what you think the issue is, if you still think there is one, as I pretty much don't understand where to look at.

**Comment by MarliesMaalderink** [comment]
Hi Danack,

You are right, I have been fiddeling with this for so long that I left out the cropping part on the command line after figuring out it was related to that. So sorry to have bothered you with this, it appears to be unexpected behaviour inside Image Magick itself.

Thank you for looking in to it.

**Comment by Danack** [comment]
no worries.
