### ISSUE TITLE
[3.5] file permissions

### ISSUE THREAD

**Issue by remicollet** [Imagick/imagick#427]
On git, at least *.stub.php have unneeded permissions

`chmod -x *.stub.php`

For pecl archive, please DON'T use windows to generate the archive

```
$ tar tvf imagick-3.4.4.tgz
-rw-r--r-- root/root     38781 2019-05-02 17:26 package.xml
-rw-r--r-- root/root      2776 2019-05-02 17:25 imagick-3.4.4/examples/polygon.php
-rw-r--r-- root/root      1576 2019-05-02 17:25 imagick-3.4.4/examples/captcha.php
-rw-r--r-- root/root       430 2019-05-02 17:25 imagick-3.4.4/examples/thumbnail.php
-rw-r--r-- root/root       651 2019-05-02 17:25 imagick-3.4.4/examples/watermark.php
...
```

But
```
$ tar tvf imagick-3.5.0RC1.tgz
-rw-r--r-- root/root     40632 2021-06-14 21:41 package.xml
-rwxrwxrwx root/root      2776 2021-06-14 21:41 imagick-3.5.0RC1/examples/polygon.php
-rwxrwxrwx root/root      1576 2021-06-14 21:41 imagick-3.5.0RC1/examples/captcha.php
-rwxrwxrwx root/root       430 2021-06-14 21:41 imagick-3.5.0RC1/examples/thumbnail.php
-rwxrwxrwx root/root       651 2021-06-14 21:41 imagick-3.5.0RC1/examples/watermark.php
...
```

**Comment by Danack** [comment]
> please DON'T use windows to generate the archive

Other than 'remembering', do you know of a sensible way I can prevent myself from doing that?

I've finally got the quite powerful Windows box I bought 4 years ago working now that WSL2 is a thing, so it's a lot faster than my even older mac, so am likely to use it more. And no, I'm not switching to linux....

**Comment by remicollet** [comment]
Perhaps @cmb69 knows a workaround to this ?

BTW, not critical... can live with it (this raise warning in package build, easy to fix)

**Comment by cmb69** [comment]
I'm not sure, but would it work when using the Linux filesystem? I, personally, have a VirtualBox VM for packaging packages.

**Comment by Danack** [comment]
> but would it work when using the Linux filesystem?

Maybe. But I had quite a few glitches when using that, which is why I switched to using a separate drive. I guess I'll just have to remember to use the mac.

Anyway, files are chmod'ed.
