### ISSUE TITLE
Missing files in 3.5.0RC1 for tests

### ISSUE THREAD

**Issue by munix9** [Imagick/imagick#429]
For information:
These files are missing in the archive https://pecl.php.net/get/imagick-3.5.0RC1.tgz for the tests:
```
tests/houghline_input_image.png
util/Float32Info.php
util/FloatInfo.php
util/functions.php
```
```
# 274_imagick_setImageAlpha.phpt - tests/../util/functions.php
# 281_imagick_houghLineImage_basic.phpt - tests/houghline_input_image.png
# 289_Imagick_setImageMask_basic.phpt - tests/houghline_input_image.png
```

**Comment by Danack** [comment]
Thanks, this was fixed in #420

And then the typo in the dir name was just fixed in 4385fd83420565ed1d6ab3c0bfb5a73d9d0b9be5

And I left an issue open to test this properly as part of the CI: https://github.com/Imagick/imagick/issues/422
