### ISSUE TITLE
Using foreach() On An Array Of Size Values Not Working - resizeImage() Function

### ISSUE THREAD

**Issue by EmilyChews** [Imagick/imagick#432]
Hi,

I have an image I want to re-size to different sizes using the `resizeImage()` function.

I'm setting a series of widths in an associative array and then looping through them with a `foreach()` loop.

When I remove the foreach loop and manually add a specific size as the width parameter (e.g. 150) it works, but when I take the values from the associate array with the loop it doesn't?

When I use a foreach loop all I get is a single image produced which is the size of the final key value (1500px) and it is incredibly blurred.

What is the best way to do multiple re-sizes (which I assume is with a loop), and do you know why this code isn't working?

    // create new object of image from image in memory/tmp_folder
    $image = new Imagick($temp);
    
    $sizesjpeg = [
      'tiny_' => 50,
      'small_' => 150,
      'medium_' => 500,
      'large_' => 1500,
    ];
    
    $destinationFolder = 'images_lib/';
    
    // image processing of different sizes from the array
    foreach ($sizesjpeg as $sizename => $size) {
    
      // setting the height to 0 means it only resizes the width thus keeping the image ratio
      $image->resizeImage($size, 0, Imagick::FILTER_LANCZOS, 1);
      $image->writeImage($destinationFolder . $file);

    }
    $image->clear();

**Comment by EmilyChews** [comment]
I found the problem - I needed to instantiate a new object each time within the loop and also set the $file variable to a new file name each time:

`
$sizesjpeg = [
  'tiny_' => 50,
  'small_' => 150,
  'medium_' => 500,
  'large_' => 1500,
];

$destinationFolder = 'images_lib/';

// image processing of different sizes from the array
foreach ($sizesjpeg as $sizename => $size) {

  $file = uniqid('', true) . time() . '.' . $ext;
  $image = new Imagick($temp);
  
  // setting the height to 0 means it only resizes the width thus keeping the image ratio
  $image->resizeImage($size, 0, Imagick::FILTER_LANCZOS, 1);
  $image->writeImage($destinationFolder . $file);

}
$image->clear();`

**Comment by Danack** [comment]
FYI, you can also use clone, rather than reopening the image, which would be a tiny bit faster

```
$image_resize = clone $image;
```
