### ISSUE TITLE
3 failing tests

### ISSUE THREAD

**Issue by utkarsh2102** [Imagick/imagick#437]
Hey,

Thanks for your work on imagick! 🎉 

I've been running tests & suddenly they've started to fail:
```
There were 3 failures:

1) /tmp/autopkgtest.FwoYHc/build.775/real-tree/imagick-3.4.4/tests/016-static-methods.phpt
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'array\n
+'sysconf(NPROCESSORS_CONF) failed: Invalid argument\n
+array\n
 array\n
 array\n
 array\n
 success'

/tmp/autopkgtest.FwoYHc/build.775/real-tree/imagick-3.4.4/tests/016-static-methods.phpt:1

2) /tmp/autopkgtest.FwoYHc/build.775/real-tree/imagick-3.4.4/tests/026_phpinfo.phpt
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
+sysconf(NPROCESSORS_CONF) failed: Invalid argument
 Ok

/tmp/autopkgtest.FwoYHc/build.775/real-tree/imagick-3.4.4/tests/026_phpinfo.phpt:1

3) /tmp/autopkgtest.FwoYHc/build.775/real-tree/imagick-3.4.4/tests/272_imagick_identifyimagetype.phpt
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
-Ok
+Fatal error: Uncaught Error: Call to undefined method Imagick::identifyImageType() in Standard input code:6
+Stack trace:
+#0 {main}
+  thrown in Standard input code on line 6

/tmp/autopkgtest.FwoYHc/build.775/real-tree/imagick-3.4.4/tests/272_imagick_identifyimagetype.phpt:25

```

I am not sure what changed. I tried to debug but couldn't really get to any place worthwhile. Do you happen to know what could be the root cause of this?

**Comment by Danack** [comment]
You're either cross-compiling and have setup something wrong, or you aren't compiling from a clean checkout, and something is left over from a previous compile, possibly from a different operating system:

> +sysconf(NPROCESSORS_CONF)

have you upgraded your operating system since the last build?

**Comment by utkarsh2102** [comment]
Hello Danack,

> have you upgraded your operating system since the last build?

That could be it. I did indeed use the newer daily LXD image (ubuntu/impish/amd64) image this morning and this is when things have started to go off the rails. I can't figure out what really it was, is there a way to do that or something?

**Comment by Danack** [comment]
Repeat the same mistake and see if you get the same error message.

Or you could just start over from a fresh checkout to get a working build.
