### ISSUE TITLE
Issue with Tiff & Custom size Images

### ISSUE THREAD

**Issue by sprabhakar93** [Imagick/imagick#440]
Hi
We are using ImageMagick plugin for Print2Metal website and we have encountered an issue when we upload a Tiff image on the website with a custom size. For this case, the saved image is of incorrect size.
Example:
We uploaded a tiff image with a custom size of 22 x 17.5 inch, but the saved image is not of the requested size (Please check the attached image).
Can you please let us know if you have any solution for this issue?
Thank you.
Kind regards,
Sandhya Prabhakar
Client Service Coordinator
![TestImage](https://user-images.githubusercontent.com/79486075/122693392-07e31680-d27d-11eb-8598-32bfda91c39e.JPG)

**Comment by Danack** [comment]
Please can you post some code for how you are creating an image and "setting it's size". 

You can use the newPseudoImage to avoid needing a source image.

```
$imagick = new Imagick();
$imagick->newPseudoImage(1000, 1200, "magick:logo");

```

I really can't comment on what is happening when I have no idea what code you are using. The image you uploaded is a jpg image, so I don't know how it relates to your issue.

**Comment by Danack** [comment]
Okay, feel free to [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) but I can't do much without that.

**Comment by sprabhakar93** [comment]
Hi Danack, 

Please find below the code we are using for creating the image and setting its size:

    //create the image object
    $image = new Imagick($imgPath);
    // resize the image to size of editor
    $image->resizeImage($imgW, $imgH, $filter, $blur, $bestFit);
    //crop image to viewport dimensions
    $image->cropImage($cropW, $cropH, $imgX1, $imgY1);
    //reset image
    $image->resetImagePage("{$cropW}x{$cropH}+0+0");
    //greyscale the image?
    if ($_POST['blackandwhite']) {
        $image->modulateImage(100, 0, 0);
    }
    //any text?
    if (trim($_POST['textoverlay']) != '') {
        $draw = new ImagickDraw();
        $text = $_POST['textoverlay'];
        $textx = $_POST['textx'] / $_POST['scalefactor'];
        $texty = ($_POST['texty'] + 20) / $_POST['scalefactor'];

        //echo "text x: $textx     text y: $texty"; die();
        $draw->setFillColor($_POST['textcolour']);
        $draw->setFont($font);
        $draw->setFontSize($font_size);
        $image->annotateImage($draw, $textx, $texty, 0, $text);
    }
   
    if ($_POST['imageshape'] == 'circle') {
        $image->vignetteImage(0, 0, 0, 0);
    }

    // if border is set, then write border to image
    if (($border_color != '') && ($border_size_px != '')) {
        $writeBorder = true;
        $image->borderImage($border_color,$border_size_px, $border_size_px);
    }

Tiff format is not supported so I was not able to attach the image. 

It will be great if you could provide your inputs on this. 

Thank you.

Kind regards, 
Sandhya Prabhakar
Client Service Coordinator

**Comment by sprabhakar93** [comment]
Hi Danack,

I have added the code to the same ticket.

Can you please check and provide your insights on this?

Thank you.

Kind regards,
Sandhya

Sandhya Prabhakar
Client Service Coordinator

**Comment by Danack** [comment]
@sprabhakar93 please either get a less terrible email client, or don't update the tickets via email. A wall of email signature text is kind of annoying.

As for the example, it gives an error:
```
Warning: Undefined variable $imgPath in /var/app/bugs/bug440/bugreport.php on line 7
```

Please contemplate this link more deeply:

> Okay, feel free to [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) but I can't do much without that.

Probably in particular, the bit of code that you think does "We uploaded a tiff image with a custom size of 22 x 17.5 inch," needs to be in the example.

**Comment by Danack** [comment]
Okay, closing until there is something I can investigate.

**Comment by sprabhakar93** [comment]
Hi Danack, 

To provide you more details on this, we are uploading images in https://shop.print2metal.com/. When a user uploads an image and selects any size, the image is cropped to the requested size using the provided code. In this case, we found that when we upload a tiff image with custom size, the image saved on the server is not of the required size. I am not able to attach the tiff image as the format is not supported.

We have provided the code which we use for uploading a tiff image and specifying the size:

$image = new Imagick();
    $image->setResourceLimit( Imagick::RESOURCETYPE_MEMORY, 33554432  );
    $image->setOption('jpeg:size', $imgW.'x'.$imgH);
    $image->readImage($imgPath);
    $image->resizeImage($imgW, $imgH, $filter, $blur, $bestFit);
    //crop image to viewport dimensions
    $image->cropImage($cropW, $cropH, $imgX1, $imgY1);
    //reset image
    $image->resetImagePage("{$cropW}x{$cropH}+0+0");
    //greyscale the image?
    if($_POST['blackandwhite'])
    {
        $image->modulateImage(100, 0, 0);;
    }
    //any text?
    if(trim($_POST['textoverlay']) != '')
    {
        $draw = new ImagickDraw();
        $text = $_POST['textoverlay'];
        $textx = $_POST['textx'] / $_POST['scalefactor'];
        $texty = ($_POST['texty'] + 20) / $_POST['scalefactor'];
        $draw->setFillColor($_POST['textcolour']);
        $draw->setFont($font);
        $draw->setFontSize( $font_size );
        $image->annotateImage($draw, $textx, $texty, 0, $text);
    }

    //create the image object
    $image = new Imagick($imgPath);
    // resize the image to size of editor
    $image->resizeImage($imgW, $imgH, $filter, $blur, $bestFit);
    //crop image to viewport dimensions
    $image->cropImage($cropW, $cropH, $imgX1, $imgY1);
    //reset image
    $image->resetImagePage("{$cropW}x{$cropH}+0+0");
    //greyscale the image?
    if ($_POST['blackandwhite']) {
        $image->modulateImage(100, 0, 0);
    }
   
    if (trim($_POST['textoverlay']) != '') {
        $draw = new ImagickDraw();
        $text = $_POST['textoverlay'];
        $textx = $_POST['textx'] / $_POST['scalefactor'];
        $texty = ($_POST['texty'] + 20) / $_POST['scalefactor'];
        //echo "text x: $textx     text y: $texty"; die();
        $draw->setFillColor($_POST['textcolour']);
        $draw->setFont($font);
        $draw->setFontSize($font_size);
        $image->annotateImage($draw, $textx, $texty, 0, $text);
    }
   
    if ($_POST['imageshape'] == 'circle') {
        $image->vignetteImage(0, 0, 0, 0);
    }
    // if border is set, then write border to image
    if (($border_color != '') && ($border_size_px != '')) {
        $writeBorder = true;
        $image->borderImage($border_color,$border_size_px, $border_size_px);
    }

Hope these details assist you in providing a solution for this issue?

Thank you. 

Kind regards,
Sandhya Prabhakar
Client Service Coordinator

**Comment by Danack** [comment]
@sprabhakar93 I need an example that runs. Neither of the pieces of code you provided run, because they both use variables that are not defined.

e.g. on this line:
```
$image->setOption('jpeg:size', $imgW.'x'.$imgH);
```

The image width and height are not defined.


On this line:
```
$image->resizeImage($imgW, $imgH, $filter, $blur, $bestFit);
```

None of those variables are set.

I can't see what you're actually setting the size to, so can't even begin to investigate the issue.

**Comment by Danack** [comment]
@sprabhakar93 Please can you ask whichever developer wrote the code to come here so I can talk to them directly, as having to pass messages through you is probably a bit of a frustrating experience for both of us.

If your developers are not allowed to discuss issues with libraries they are using online, please let me know.

**Comment by Danack** [comment]
Closing again, as I can't investigate without working code example.
