### ISSUE TITLE
PECL Package obsolete?

### ISSUE THREAD

**Issue by ghnp5** [Imagick/imagick#444]
Checking yum updates (remi repository), seems that imagick is becoming obsolete:

```
...
php74-php-xml.x86_64                    7.4.21-1.el7.remi           remi
Obsoleting Packages
php74-php-pecl-imagick-im6.x86_64       3.5.0-1.el7.remi            remi
    php74-php-pecl-imagick.x86_64       3.4.4-17.el7.remi           @remi
```

Does this mean that Imagick PECL package is now obsolete, or is this something I have to check with the remi repository?

If it's becoming obsolete, what's the alternative API to use?

Thank you.

**Comment by Danack** [comment]
I don' have much idea. Remi did change the name of some things, so that people can choose either ImageMagick 6 or 7 support. https://github.com/remicollet/remirepo/issues/179

> is this something I have to check with the remi repository?

Yes.
