### ISSUE TITLE
'__config' file not found

### ISSUE THREAD

**Issue by Maritho** [Imagick/imagick#446]
I don't know what's going on, I stay up late because of this while doing make, I get an error like this in MacOS Catalina

/usr/local/include/stdint.h:106:10: fatal error: '__config' file not found
#include <__config>
         ^~~~~~~~~~
1 error generated.
make: *** [imagick_file.lo] Error 1

Can someone help me?

**Comment by Danack** [comment]
No real idea, but I'd recommend checking out code in a fresh directory and doing a full build from scratch.

That looks a bit like some bit of generated config has been preserved from a previous build, and the compiler on your system has changed since it was generated.

**Comment by Danack** [comment]
Sorry, not a problem in Imagick.
