### ISSUE TITLE
Tag 3.5.1 for macos build

### ISSUE THREAD

**Issue by Nek-** [Imagick/imagick#449]
Hello,

The configuration [has been updated in master branch](https://github.com/Imagick/imagick/commit/c9319d19410457b2bc07e9cdff1edf3983e7dfcf) for macos. Is it possible to release this version to allow installation with pecl?

I don't know the process of this repository, my notice may be totally irrelevant, I apologize for that.

Thank you! (also thank you very much for the maintenance of this package!)

**Comment by Danack** [comment]
Good idea.

3.5.1RC1 is released. If there are no complaints, I'll release the 3.5.1 on thursday.

**Comment by Nek-** [comment]
```
$ pecl install imagick-3.5.1RC1
...
...
...
Build process completed successfully
Installing '/usr/local/Cellar/php/8.0.7/include/php/ext/imagick/php_imagick_shared.h'
Installing '/usr/local/Cellar/php/8.0.7/pecl/20200930/imagick.so'
install ok: channel://pecl.php.net/imagick-3.5.1RC1
Extension imagick enabled in php.ini
```

Worked like a charm on my side :) .

**Comment by EldarAgalarov** [comment]
@Danack You tagged 3.5.1RC1 as 3.5.0RC1

**Comment by Danack** [comment]
@EldarAgalarov Thanks - but actually I'd forgotten to tag 3.5.0RC1 at all, and had gone back to tag it.

The pecl release process is separate from the tags on Github, and I'd forgotten to add the tags to git. The tags are only for reference and for debugging purposes - the canonical release is always the tgz files on pecl.php.net.

Anyway 3.5.1 release is on pecl now - windows builds will appear when the machine that builds them, er, builds them.
