### ISSUE TITLE
Imagick::getImageInterlaceScheme is deprecated

### ISSUE THREAD

**Issue by ajakov** [Imagick/imagick#455]
Hi, 

`Imagick::getImageInterlaceScheme` is deprecated but I can't find a way to replace it in the code. 
I tried with `Imagick::getInterlaceScheme` but it returns different values for the same image. 

What would be the proper way to replace this function calls?

Thank you!

**Comment by Danack** [comment]
Please can you post the image you're using, and some code that shows what you're seeing, as that avoids me having to spend time duplicating what you already have.

**Comment by ajakov** [comment]
Yes, I expected that, too. 

Pushed a simple example to this repo: https://github.com/ajakov/imagick-interlace-example
Image is interlaced, `getImageInterlaceScheme` returns 7 (as expected), while `getInterlaceScheme` returns 1 (not interlaced)

**Comment by Danack** [comment]
So, after having a quick look, I have no idea what's going on.

It's not obvious why the function was deprecated. The [commit](https://github.com/Imagick/imagick/commit/d5ba97703093d08fa77d4c8d5686f1d1f519df9f#diff-3b972e6d76bc3829f8a33ec8f288b23f601d0069f16c0074dd1519330e07b0f1R6219) was also deprecating some other functions which were removed from ImageMagick, but both of the underlying functions appear to still be available in the latest ImageMagick, and don't appear to be deprecated. It's possible it was deprecated but then the upstream maintainers of ImageMagick un-deprecated it.

I'm tempted to just remove that deprecation notice, unless @mkoppanen can recall from the days of his youth, why getImageInterlaceScheme is deprecated?


And returning a different value still looks like a bug. The two functions internally call:

```
getImageInterlaceScheme  => MagickGetImageInterlaceScheme => return(wand->images->interlace);

getInterlaceScheme  => MagickGetInterlaceScheme(MagickWand *wand) => return(wand->image_info->interlace);
```

I'll have to report an issue upstream, as it sounds like a bug to me.

**Comment by Danack** [comment]
Upstream: https://github.com/ImageMagick/ImageMagick/discussions/4171

**Comment by ajakov** [comment]
Great, thank you for escalating :)

**Comment by Danack** [comment]
Ok, so Imagick::getImageInterlaceScheme will be un-deprecated in the next release which happen 'soon'.

**Comment by ajakov** [comment]
Great, thank you!
