### ISSUE TITLE
Incorrect / outdated proto for Imagick::profileImage

### ISSUE THREAD

**Issue by christeredvartsen** [Imagick/imagick#456]
Over on https://www.php.net/manual/en/imagick.profileimage.php the description for the `profileImage` method is:

    public Imagick::profileImage(string $name, string $profile): bool

and the description reads:

    Adds or removes a ICC, IPTC, or generic profile from an image. If the profile is NULL, it is removed from the image otherwise added. Use a name of '*' and a profile of NULL to remove all profiles from the image.

Not sure if this is pulled from the source of this extension, but the same content can be found in `imagick_class.c`.

The following snippet, that should be valid code according to the documentation, causes a fatal error when ran with strict types:

```php
<?php declare(strict_types=1);
$imagick = new Imagic('image.png');
$imagick->profileImage('*', null);
```

causes:

```
PHP Fatal error:  Uncaught TypeError: Imagick::profileimage() expects parameter 2 to be string, null given
```

The same error occurs on php-7.4 and php-8.0.

**Comment by Danack** [comment]
Thanks.

The function wasn't intentionally changed but it looks like through a combination of internal changes, things became broken. From looking at the code, it appears that previously null was being silently cast to an empty string, which coincidentally has the same effect as null.

This will need a bugfix release to fix, but if you're desperate to have it working, I think `$imagick->profileImage('*', "");` may be a workaround.

**Comment by christeredvartsen** [comment]
> This will need a bugfix release to fix, but if you're desperate to have it working, I think $imagick->profileImage('*', ""); may be a workaround.

This seems to be working, thanks.

**Comment by Danack** [comment]
This should be fixed in the next release. tbh, this is a bit of the extension that could really do with more tests, but I'll track that in a separate issue - #464
