### ISSUE TITLE
Failed test with latest 6.9.12-22 and 7.1.0-8

### ISSUE THREAD

**Issue by remicollet** [Imagick/imagick#457]
```
========DIFF========
002+ PNG
002- png
========DONE========
FAIL Test reading properties [tests/009_properties.phpt] 
```

Seems minor, case related

**Comment by remicollet** [comment]
Related to 
https://github.com/ImageMagick/ImageMagick/commit/772e98c6431d9999830acfe67eb95857530317d5
https://github.com/ImageMagick/ImageMagick/issues/4235

**Comment by yunal** [comment]
I'm just a sysop trying to write good policies for ImageMagick installs.  Having IM upper case format names to match an idea of a "canonical" format label that matches what the coders and delegates use seems friendly. It's hard for me to see any good use case where "pNg" should be different from "PNG" and it makes writing and reading policies unfriendly.

https://en.wikipedia.org/wiki/Robustness_principle

In any case, ImageMagick is fantastically usefull software and makes evertyhing easier than netpbm :-)
