### ISSUE TITLE
Cant't install imagick

### ISSUE THREAD

**Issue by ideaviewes** [Imagick/imagick#473]
Imagick was compiled against ImageMagick version 1799 but version 1808 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
I cant find ImageMagick version 1799 any where
how to get it?

**Comment by Danack** [comment]
All from these two places:

https://windows.php.net/downloads/pecl/releases/imagick/
https://windows.php.net/downloads/pecl/deps/

**Comment by birenjung** [comment]
ImageMagick 7.1.0-18 Q16 x64 2021-12-14 https://imagemagick.org. i could not find this to download. my extension is compiled with this version.

**Comment by Danack** [comment]
@birenjung Maybe ask whoever compiled the extension to also provide that exact version of ImageMagick?
