### ISSUE TITLE
how to remove the transparent section in an image?

### ISSUE THREAD

**Issue by ideaviewes** [Imagick/imagick#486]
how to remove the transparent section in an image with imagick，or how to find the non-transparent section

**Comment by Danack** [comment]
Possibly [Imagick::trimImage](https://phpimagick.com/Imagick/trimImage?fuzz=0.1&color=rgb(39%2C%20194%2C%20255)).

But it's not obvious to me what you want exactly. Please post an example input image and hand made version of what output you want, if trimImage doesn't do what you want.

**Comment by ideaviewes** [comment]
@Danack ,Thank you, it works for me.
