### ISSUE TITLE
Consider adding support for composites with masks

### ISSUE THREAD

**Issue by marcospassos** [Imagick/imagick#49]
Hi folks!

Currently, there is no way to achieve the same result obtained through the following command:

```
convert ./a.png ./b.png ./c.png  -virtual-pixel transparent -channel rgba -alpha on -background transparent -define compose:args=300x53.033 -compose displace -composite ./final.png
```

a.png
![a](https://cloud.githubusercontent.com/assets/943036/4395872/5ba7ad00-442f-11e4-9496-ecd19948eace.png)

b.png
![Overlay](https://cloud.githubusercontent.com/assets/943036/4395860/3df162ba-442f-11e4-8bb0-05195526cb85.png)

c.png
![Mask](https://cloud.githubusercontent.com/assets/943036/4395861/3df2e5d6-442f-11e4-916b-94283ef114ce.png)

Result:
![Result obtained though command line](https://cloud.githubusercontent.com/assets/943036/4395721/c05ded2e-442d-11e4-8d19-b07f8920070d.png)

Where `a.png` is a base image, `b.png` is the overlay and `c.png` is the gray-scale 'mask'. For achieving this result, I've to execute all manipulations which are supported by the extension, write the image in disk and then execute this command through the exec function, which is a terrible workaround.

The following snippet does not work:

``` php
$a = new Imagick('../a.png');
$b = new Imagick('../b.png');
$c = new Imagick('../c.png');

$a->setImageVirtualPixelMethod(Imagick::VIRTUALPIXELMETHOD_TRANSPARENT);
$a->setImageBackgroundColor(new ImagickPixel('none'));
$a->setOption('compose:args', '300x53.033');
$a->compositeImage($c, Imagick::COMPOSITE_DSTIN, 0, 0, Imagick::CHANNEL_ALPHA);
$a->compositeImage($b, Imagick::COMPOSITE_DISPLACE, 0, 0);
```

Result:
![Result obtained though PHP](https://cloud.githubusercontent.com/assets/943036/4395737/f475502a-442d-11e4-8631-b425ee7094a2.png)

**Comment by mreichenbach-igniti** [comment]
@Danack @marcospassos Was there any change on how to use the displacement via Imagick? It was working fine with ImageMagick 6.7.9 + Imagick 3.2.0, but it results in a different result with ImageMagick 6.9.10 + Imagick 3.4.3. Details can be found in my stackoverflow question: https://stackoverflow.com/questions/57722353/apply-displacement-map-via-imagick-after-version-update

**Comment by mreichenbach-igniti** [comment]
It seems that this function is completely ignored somehow:
`$displaceMask->setImageArtifact('compose:args', "300x53.033");`
At least nothing changes if I do not set the compose arguments.

**Comment by mreichenbach-igniti** [comment]
I found this issue in the changelog of ImageMagick: https://github.com/ImageMagick/ImageMagick/issues/597
--> to solve the issue, I had to set the compose arguments not on the displacement map, but instead on the source image. Then It was working fine.
