### ISSUE TITLE
Unable to initialize module on PHP 8.1.0 (Mac OS Apple M1)

### ISSUE THREAD

**Issue by agussetyar** [Imagick/imagick#509]
Hi, I recently updated my PHP Version to the latest version which is PHP 8.1.0

When i rebuilt php imagick using this tutorial
https://samsonasik.wordpress.com/2021/01/04/install-imagick-extension-for-php8-in-macos-big-sur/

I have an error like this
```
Warning: PHP Startup: imagick: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0
Configuration File (php.ini) Path: /opt/homebrew/etc/php/8.1
Loaded Configuration File:         /opt/homebrew/etc/php/8.1/php.ini
Scan for additional .ini files in: /opt/homebrew/etc/php/8.1/conf.d
Additional .ini files parsed:      /opt/homebrew/etc/php/8.1/conf.d/ext-opcache.ini
```

I already reinstall imagemagick module from homebrew, but the error still exists.

Should i wait for a new update version of imagick to work with PHP 8.1.0?

Because, while i'm using PHP 8.0.x, I dont have problem like this.

**Comment by Danack** [comment]
> Module compiled with module API=20200930
> PHP    compiled with module API=20210902

I think you either:
* didn't run phize.
* didn't run ./configure after running phpize.
* ran phpize before installing PHP 8
* or failed to run make install.

Basically the built library that PHP is finding was built against PHP 8.0.

**Comment by agussetyar** [comment]
I run every single steps on that website.

I can confirm if my PHP is on 8.1.0 while compiling that imagick source.

This is my phpize version
```
Configuring for:
PHP Api Version:         20210902
Zend Module Api No:      20210902
Zend Extension Api No:   420210902
```

I'm running ./configure with option to php-config 8.1 path

**Comment by agussetyar** [comment]
The problem is solved!

I deleted the imagick source from my own server and re-clone the repository, after that i re-compile and normal.
I think the problem is config.h after compilation didnt make any changes.

**Comment by Danack** [comment]
aka "didn't run ./configure after running phpize." probably.

anyway, glad it's sorted.
