### ISSUE TITLE
imagick.so.so

### ISSUE THREAD

**Issue by signmeuptwice** [Imagick/imagick#510]
I did a `brew upgrade`, then `pecl install imagick` I have php 8.1 on osx 12.x

Imagick is not working anymore

`php --ini` gives

    PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/local/lib/php/pecl/20210902/imagick.so (dlopen(/usr/local/lib/php/pecl/20210902/imagick.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210902/imagick.so' (no such file), '/usr/local/lib/imagick.so' (no such file), '/usr/lib/imagick.so' (no such file)), /usr/local/lib/php/pecl/20210902/imagick.so.so (dlopen(/usr/local/lib/php/pecl/20210902/imagick.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210902/imagick.so.so' (no such file), '/usr/local/lib/imagick.so.so' (no such file), '/usr/lib/imagick.so.so' (no such file))) in Unknown on line 0
    
    Warning: PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/local/lib/php/pecl/20210902/imagick.so (dlopen(/usr/local/lib/php/pecl/20210902/imagick.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210902/imagick.so' (no such file), '/usr/local/lib/imagick.so' (no such file), '/usr/lib/imagick.so' (no such file)), /usr/local/lib/php/pecl/20210902/imagick.so.so (dlopen(/usr/local/lib/php/pecl/20210902/imagick.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210902/imagick.so.so' (no such file), '/usr/local/lib/imagick.so.so' (no such file), '/usr/lib/imagick.so.so' (no such file))) in Unknown on line 0
    Configuration File (php.ini) Path: /usr/local/etc/php/8.1
    Loaded Configuration File:         /usr/local/etc/php/8.1/php.ini
    Scan for additional .ini files in: /usr/local/etc/php/8.1/conf.d
    Additional .ini files parsed:      /usr/local/etc/php/8.1/conf.d/ext-opcache.ini

Notice the `'/usr/local/lib/imagick.so.so`
I have a file `'/usr/local/lib/imagick.so` how can I link this one ?

**Comment by Danack** [comment]
maybe reintall php + imagick from scratch.

But then ask for help at https://github.com/shivammathur/homebrew-php

I don't know anything about Brew myself.
