### ISSUE TITLE
Unable to compile imagick from source 

### ISSUE THREAD

**Issue by mickaelperrin** [Imagick/imagick#513]
Hi,

I am struggling in compiling imagick on my custom image of php based on php:7.4-fpm-alpine.

Imagemagick is also compiled from source.

I have created this repository https://github.com/mickaelperrin/imagick-build-error with a minimal Dockerfile showing the problem.

The build fails with the following errors:

```
#8 3.852 /usr/src/php/ext/imagick/php_imagick_defs.h:25:12: fatal error: MagickWand/MagickWand.h: No such file or directory
#8 3.852    25 | #  include <MagickWand/MagickWand.h>
#8 3.852       |            ^~~~~~~~~~~~~~~~~~~~~~~~~
```

I guess this could be related to the following lines in the log:
```
#8 2.581 checking ImageMagick MagickWand API configuration program... checking Testing /usr/local/bin/MagickWand-config... It exists
#8 2.581 found in /usr/local/bin/MagickWand-config
#8 2.584 checking if ImageMagick version is at least 6.2.4... found version 7.1.0-17 Q16 HDRI
#8 2.584 checking for MagickWand.h or magick-wand.h header... user location /usr/local/include/ImageMagick-7/MagickWand/MagickWand.h
#8 2.587 /usr/local/bin/MagickWand-config: line 53: --libs: not found
#8 2.588 /usr/local/bin/MagickWand-config: line 41: --cflags: not found
```

Any idea of what I am doing wrong ?

Thanks for any help.

**Comment by Danack** [comment]
The [m4 file][https://github.com/Imagick/imagick/blob/86d95fed787d60db110ccfeb2d89ec53f1d1f5f7/imagemagick.m4#L94-L98) is testing to see if the MagickWand-config program exists at various places. 

```
#8 2.581 checking ImageMagick MagickWand API configuration program... checking Testing /usr/local/bin/MagickWand-config... It exists
#8 2.581 found in /usr/local/bin/MagickWand-config
...
#8 2.587 /usr/local/bin/MagickWand-config: line 53: --libs: not found
```
Apparently it finds it at /usr/local/bin/MagickWand-config, but then gives a 'not found' error when run.

Can you try running it directly with the command `/usr/local/bin/MagickWand-config --libs` and see what the output is. For me it's `-L/usr/local/lib -lMagickWand-7.Q16HDRI -lMagickCore-7.Q16HDRI`

The call to that program should check for an error code I guess.....but that would just stop confusion and not actually make it work.

It's possibly something silly like that program exists, but isn't executable for some reason.

**Comment by Danack** [comment]
btw, I've only recently started having to do something like `&& ldconfig /usr/local/lib \` as you have in your build (so I don't really know why it's required sometimes) but it's kind of weird seeing it before the ImageMagick library is built, as afaik, it looks at the libraries available in the relevant directories.

**Comment by mickaelperrin** [comment]
@Danack Thanks a lot for your answers.

It appears that I "simply" need to install pkgconfig and autoconf **before** the compilation of imagemagick.

**Comment by Danack** [comment]
That's one way to solve it. The build process should work without pkgconfig, by using the /usr/local/bin/MagickWand-config program directly.

But fyi, I was unable to build the container, as it gives an error in compiling libwebp.

```
config.status: error: in `/usr/src/libwebp':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.
```
