### ISSUE TITLE
Imagick PDF page conversion to JPG works properly only for first page

### ISSUE THREAD

**Issue by willianrod** [Imagick/imagick#514]
I'm trying to convert every page of a PDF (5 pages in my case) to JPEG, but only the first page is converted properly

The $contractBranch is already splitted in pages, and it's normal as I saved the PDF and JPG versions images inside this and the PDF was saved perfectly and the JPEG one was buggy, looking like all bytes for a page was splited in 3.

```php
/**
     * @param ContractShopkeeper $contractBranch
     * @throws InternalErrorException
     * @throws RequestFenixApiException
     * @throws ImagickException
     */
    public function uploadContract(ContractShopkeeper $contractBranch): void
    {
        foreach ($contractBranch->getContrato() as $i => $contract) {
            $index      = $i + 1;
            $remoteName = 'file-' . $index . '.jpeg';

            $file = $this->convertBase64->decodeBase64($contract->getPage());
            $file = $this->convertFileToImage->convertToJPG($file);
            // Before upload the image is already broken
            $this->uploadFileFenixService->uploadFile($file, $remoteName);
        }
    }
```

And this is what convertToJPG is doing

```php
    /**
     * @param string $file
     * @return Imagick
     * @throws InternalErrorException
     */
    public function convertToJPG(string $file): Imagick
    {
        try {
            $imagick = new Imagick();
            $imagick->readImageBlob($file);
            $imagick->setImageFormat('jpeg');

            return $imagick;
        } catch (Exception $e) {
            throw new InternalErrorException(
                "Ocorreu um erro ao converter o arquivo para JPG/JPEG!",
                500,
                $e->getMessage()
            );
        }
    }
```

The first looks normal, but the rest is completly buggy, like this:

![](https://i.stack.imgur.com/Hsapn.png)

This is a sample of how it should be:
![](https://i.stack.imgur.com/n2AHU.png)

**Comment by Danack** [comment]
Please can you try validating the PDF as valid against one of these services https://www.pdfen.com/pdf-a-validator or https://avepdf.com/pdfa-validation . Reasonable chance it might just be an invalid doc.

To be clear, is this just a single PDF that is showing the problem or all PDFs?

But then the code example you gave isn't runnable, and doesn't explicitly do any image output, so I can't see what it's actually doing.  

Can you make a runnable reproduce case with something very much like:

```
$imagick = new Imagick("test.pdf");

for ($page = 0; $page< $imagick->count() ; $page += 1) {
    $imagick->setIteratorIndex($firstLayer);
    $page_imagick = $imagick->getimage();
    $page_imagick->setImageFormat("jpeg");
    $page_imagick->writeImage("test_output_$page.jpg");
}
```

**Comment by WillianRod** [comment]
I don't know how, don't know why, but in the homologation machine works. Must be something with my S.O or something else. The same files when running in the same environment as production works flawlessly.

Thank you so much for your attention, we spend 2 days trying to figure it out, because we didn't see anyone reporting something like that on the internet

**Comment by Danack** [comment]
If it's working on one machine, but not on another, that sounds a lot like you have a bad version of one of the pieces of software involved.

This is one reason why people like to use containers or stuff like chef/puppet, to make sure the same version of software is running on all your machines.

btw there's a reasonable chance that it's ghostscript that is the piece of software that's needs to be updated.

**Comment by Danack** [comment]
Closing as I don't think there's anything for me to do.
