### ISSUE TITLE
setImageAlpha has an off by 1 / pow(2, 17)

### ISSUE THREAD

**Issue by Danack** [Imagick/imagick#519]
relevant commit to xfail the failing test: https://github.com/Imagick/imagick/commit/79acec63f284ac960f24e8057a35824e6b25a097

```
001+ Pixel values appear incorrect for pixelType 3 channel:A
001- Ok
002+ ┌──────┬──────────┬─────────────────────────┐
003+ │ Sign │ Exponent │ Mantissa                │
004+ │    0 │ 01111110 │ 00000000000000000000000 │
005+ │    0 │ 01111110 │ 00000000000000010000000 │
006+ └──────┴──────────┴─────────────────────────┘
007+ Pixel values appear incorrect for pixelType 2 channel:A
008+ ┌──────┬─────────────┬──────────────────────────────────────────────────────┐
009+ │ Sign │ Exponent    │ Mantissa                                             │
010+ │    0 │ 01111111110 │ 0000000000000000000000000000000000000000000000000000 │
011+ │    0 │ 01111111110 │ 0000000000000001000000000000000100000000000000010000 │
012+ └──────┴─────────────┴──────────────────────────────────────────────────────┘
013+ Ok
```

same value for both 32 and 64 bit exports.

**Comment by Danack** [comment]
Fixed by 224734cbf0907d40799040fc856349e930c3d7bd

For future reference off by 1/ 2^17 = an in between error...

**Comment by andypost** [comment]
The fix caused failure on PHP 8.1 on 32-bit arches

```
001+ Deprecated: Implicit conversion from float 4294967295 to int loses precision in /builds/alpine/aports/testing/php81-pecl-imagick/src/imagick-3.7.0RC1/util/functions.php on line 229
001- Ok
002+ 
003+ Deprecated: Implicit conversion from float 4294967295 to int loses precision in /builds/alpine/aports/testing/php81-pecl-imagick/src/imagick-3.7.0RC1/util/functions.php on line 237
```

**Comment by Danack** [comment]
Do you have a docker file that you can share for testing on  a 32bit arch?

Also, can you test [if this commit fixes it](https://github.com/Imagick/imagick/commit/9352cc3a587c91c155cfbc7ca4a2a3688d21b686) ?

**Comment by andypost** [comment]
@Danack Thank you a lot, the commit works for me https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/29309

PS: there's docker image `alpinelinux/alpine-gitlab-ci:latest-armv7` which needs to point `--platform=linux/arm/v7` argument, also alpine using `doas` instead of `sudo` now. For php81 you need to add "community" and "testing" repos to `doas vi /etc/apk/repositories`
