### ISSUE TITLE
How to determine which ImageMagick jibes with the latest Imagick

### ISSUE THREAD

**Issue by tmb-github** [Imagick/imagick#522]
I've installed the new XAMPP (64bit) with PHP 8.1.1 on Windows (64bit).

I've downloaded the necessary dependencies as indicated in the README:

http://windows.php.net/downloads/pecl/releases/imagick/
http://windows.php.net/downloads/pecl/deps/

What I can't determine is which ImageMagick the imagick.dll was compiled against in order to choose the right version of ImageMagick to install from the Windows Binary listing here:

https://imagemagick.org/script/download.php

How do I determine which version to install?

**Comment by tmb-github** [comment]
Aha! The reason it wasn't working was that I was using the Imagick for PHP 8.0, which is what's at the supplied link. 

The versions of Imagick for PHP 8.1 are here in the snaps folder: https://windows.php.net/downloads/pecl/snaps/imagick/3.6.0/

It works on my system, if you're waiting for use-case testing before releasing fully.

**Comment by Danack** [comment]
> How do I determine which version to install?

The zip files of releases for Windows contains all of the built ImageMagick dll's that should be used.

The file configure.xml in the config directory in the zip file includes an entry for which version of ImageMagick was used to make the build.
