### ISSUE TITLE
getImageColorspace() and getColorspace() is returning wrong values - mapping issue?

### ISSUE THREAD

**Issue by brusch** [Imagick/imagick#524]
When calling `getImageColorspace()` on a SRGB image, the return value `13` (`COLORSPACE_SRGB`) is expected but `23` (`COLORSPACE_LUV`)  is returned. Same for CMK, expected `12` actual value is `2`. 

Environment: 
```
imagick module version | 3.6.0
imagick classes | Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version | ImageMagick 7.1.0-19 Q16-HDRI x86_64 2021-12-22 https://imagemagick.org
Imagick using ImageMagick library version | ImageMagick 7.1.0-19 Q16-HDRI x86_64 2021-12-22 https://imagemagick.org
ImageMagick copyright | (C) 1999-2021 ImageMagick Studio LLC
ImageMagick release date | 2021-12-22
```

**Comment by Danack** [comment]
> When calling getImageColorspace() on a SRGB image, the return value 13 (COLORSPACE_SRGB) is expected but 23 (COLORSPACE_LUV)

Where are you getting that expectation from?

The constants come from the ImageMagick library itself, but they aren't guaranteed to be the same across different versions of the library.

Running the code below gives `23 : COLORSPACE_SRGB` for a similar version of ImageMagick.


```
$imagick = new Imagick(__DIR__ . "/Biter_500.jpg");

echo "getImageColorspace: " . $imagick->getImageColorspace() . "\n";
echo "getColorspace: " . $imagick->getColorspace() . "\n";

$rc = new ReflectionClass(Imagick::class);

$constants = $rc->getConstants();

foreach ($constants as $name => $value) {
    if (strpos($name, 'COLORSPACE') === 0) {
        $colorspaces[$value] = $name;
    }
}

ksort($colorspaces);

foreach ($colorspaces as $value => $name) {
    printf("%s : %s\n", $value, $name);
}
```

**Comment by Danack** [comment]
btw I can't see Pimcore sponsoring me yet. Please can you do so at: https://github.com/sponsors/danack ?

**Comment by brusch** [comment]
@Danack Thanks for looking into this - it seems that there's something else completely wrong 😊 - sorry for bothering you. Happy new year! 🎉
