### ISSUE TITLE
Imagick Codesigning issue on MacOS Monterey

### ISSUE THREAD

**Issue by SirOlaoluwani** [Imagick/imagick#535]
I have tried to install Imagick first through Homebrew and also directly as specified in the docs and both times I keep getting stuck with the following errors

Unable to load dynamic library 'imagick.so' (tried: /usr/local/lib/php/pecl/20190902/imagick.so (dlopen(/usr/local/lib/php/pecl/20190902/imagick.so, 0x0009): tried: '/usr/local/lib/php/pecl/20190902/imagick.so' (code signature in &lt;B734AEB2-1EB5-33D3-B2D2-E79937242626&gt; '/usr/local/lib/php/pecl/20190902/imagick.so' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/usr/lib/imagick.so' (no such file)), /usr/local/lib/php/pecl/20190902/imagick.so.so (dlopen(/usr/local/lib/php/pecl/20190902/imagick.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20190902/imagick.so.so' (no such file), '/usr/lib/imagick.so.so' (no such file))) in Unknown on line 0

When I run `php -m` I can see imagick listed but I can't find it listed in `phpinfo()`.

I think it requires me to codesign imagick, I need to know how I can go about that.

Thanks

**Comment by Danack** [comment]
> When I run php -m I can see imagick listed but I can't find it listed in phpinfo().

When you say in phpinfo() is that in a browser? php -m is on the command line, and that bit of what you're seeing would be consistent with having `extension=imagick.so` in the ini file used by php on the command line, but not having it in the ini file used by php-fpm. 

I have absolutely no idea about code-signing tbh...

**Comment by Danack** [comment]
maybe read this - https://www.simplified.guide/macos/apache-php-homebrew-codesign and let me know how it goes?

**Comment by SirOlaoluwani** [comment]
> maybe read this - https://www.simplified.guide/macos/apache-php-homebrew-codesign and let me know how it goes?

Thanks for your response @Danack. I already used this article to codesign the php7.4 I installed using homebrew. 

On Mac OS Monterey it is mandatory to codesign PHP when it is to be used with the built-in apache.

I may have to remove the built-in apache and install apache with homebrew, maybe that could solve my problem.

**Comment by Danack** [comment]
> to be used with the built-in apache.

I'd really recommend using docker for managing your local dev environment. It just works a lot more reliably than other ways of installing PHP, and projects can be shared with other people.

I realise that getting started with PHP is annoying compared to other languages, but I don't really have bandwidth to spare, so going to close this issue as it's not really Imagick's fault.
