### ISSUE TITLE
Error with pecl compiling

### ISSUE THREAD

**Issue by grem79** [Imagick/imagick#536]
Hi,

I'm trying to compile imagick for my php docker container. 
I'm using the following code: 
RUN git clone https://github.com/Imagick/imagick.git \
  && cd imagick \
  && pecl install package.xml \
  && cd .. \
  && rm -rf imagick \

But I got the following errors when I use the "pecl install package.xml" command: 
parsePackageName(): invalid package name "package.xml" in "package.xml"
tag <file> in context "<dir name="tests">" has no attribute "role"
Parsing of package.xml from file "package.xml" failed
install failed

Can you fix it :) ? 

Thanks !

**Comment by grem79** [comment]
I try to "play" it manually, I got the same output. So I suppose your recent changes on package.xml broke something.

**Comment by grem79** [comment]
Just found: 
The attribute role is missing on  <file name="166_Imagick_waveImageWithMethod_basic.phpt" /> (line 240)

**Comment by grem79** [comment]
I found something else, but I don't know if it has an impact: line 218, the code indentation is not well formed ...

**Comment by Danack** [comment]
Hi @grem79,

It looks like I've forgotten to merge either develop or 3.7.0 to master. I'm in the process of doing that now.... 

Out of curiousity, how come you're not using PECL to do the install? I mean other than PECL is a POS that no-one should be using.

**Comment by grem79** [comment]
@Danack : thx for your answer. 

Good question :-)... I don't remember why exactly ... I'm using mailcow on my personal server. But I'm using my php Dockerfile (I need mysqli, not provided by default and some other php extensions). I had a problem once using PECL and I found that way to fix... 
So, you're right : I'm going to rollback to PECL repos instead of GitHub repos......

**Comment by grem79** [comment]
I think I found my inspiration here:
https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/phpfpm/Dockerfile#L52 ;)

**Comment by Danack** [comment]
Cool. Well anyway, there is now a test to make sure the package.xml is valid.


https://github.com/Imagick/imagick/blob/b1c0b7033870f71aa54a72f43c200eb2ac70205f/validate_package.sh
