### ISSUE TITLE
imagick::pingImageBlob error message

### ISSUE THREAD

**Issue by ifjkovacsik** [Imagick/imagick#541]
Hello Community,

I am currently developing a system in which I convert pdf files to jpeg format. The pdf file is placed in a variable. I want to check its contents before I open it. To do this, I use the pingImageBlob method. But he writes a mistake. While readImageBlob works without any errors.

source:
$pdf = file_get_contents('akarmi.pdf');
$im = new \Imagick();
$im->setResolution(300, 300);
try {
  if (!$im->pingImageBlob($pdf)) {
    return 0;  
  }
}catch( \ImagickException $e) {
  echo $e;

/* output:
ImagickException: UnableToCreateTemporaryFile '': No such file or directory @ error/pdf.c/ReadPDFImage/461 in application.php:8312
*/

}
$im->readImageBlob($pdf);
$oldalak = $im->getNumberImages();
$im->clear();
$im->destroy();

Without pingImageBlob method:
$pdf = file_get_contents('akarmi.pdf');
$im = new \Imagick();
$im->setResolution(300, 300);
try {
  if (!$im->readImageBlob($pdf)) {
    return 0;  
  }
}catch( \ImagickException $e) {
  echo $e;
}
$oldalak = $im->getNumberImages();
$im->clear();
$im->destroy();

output: No error

Thank you in advance
Tamás

**Comment by Danack** [comment]
Hi @ifjkovacsik,

This sounds like it could be a problem local to your machine. To investigated please can you change:

```
$pdf = file_get_contents('akarmi.pdf');
$im = new \Imagick();
```

to something like:

```
$pdf = file_get_contents('akarmi.pdf');
if ($pdf === false) {
    echo "Failed to read image.";
    exit(-1);
    $im = new \Imagick();
}
```

Just to double-check the PDF is accessible to PHP.


If that doesn't reveal anything, please can you run some code like the below:
```
$dirname = sys_get_temp_dir() . '/imagick_test';

$dir = mkdir($dirname, 0755);

var_dump($dir);

$temp_file = tempnam($dirname, 'imagick');
echo "\n";

echo $temp_file;
echo "\n";
echo "\n";
```

to test whether PHP is able to create directories in the tmp folder for your system. I suspect it's failing to do that.

**Comment by Danack** [comment]
OK. I'm going to close this as I don't think it's a bug in Imagick and is just a problem local to your machine.
