### ISSUE TITLE
Imagick svg to png,the png pic has the black border,how to fix?

### ISSUE THREAD

**Issue by wilsonchen85** [Imagick/imagick#556]
Imagick svg to png,the png pic has the black border,how to fix?
That's the code:

```
$im = new Imagick($file_name);
$svg = file_get_contents($file_name);
$svg = '<?xml version="1.0" encoding="UTF-8" standalone="no"?>'.$svg;
$im->setBackgroundColor(new ImagickPixel('transparent'));
$im->readImageBlob($svg);

$im->setImageFormat("png24");
$srcImage = $im->getImageGeometry();
$im->resizeImage($srcImage['width'], $srcImage['height'], imagick::FILTER_LANCZOS, 1, false);
$topng_name = date('YmdHis').mt_rand(10000,99999);
$im->writeImage($path.'/'.$topng_name.'.png');
$im->clear();
$im->destroy();
```

php version:7.2.33
imagick version:3.4.4
Can somebody help me?thank you...

**Comment by Danack** [comment]
Please can you post the SVG you are trying with?

**Comment by wilsonchen85** [comment]
ok
![2022041822223929269](https://user-images.githubusercontent.com/13084653/183455835-7b20d77a-33f1-44d1-b856-a0bacc738fd3.svg)

**Comment by wilsonchen85** [comment]
ok
i.You can see the png image has black border everywhere.This is an abnormal phenomenon
ii.Imagick version:3.4.4


![2022080921171073290](https://user-images.githubusercontent.com/13084653/183656992-84c97e59-5f8c-4ab0-a8f3-d0940f19cc99.png)

![微信图片_20220809212018](https://user-images.githubusercontent.com/13084653/183657180-3702fb21-1ff1-46d1-afae-b9998bf3ee3f.png)

**Comment by wilsonchen85** [comment]
> That seems to be converted correctly for me. Please can you:
> 
> i. Post the output image you are getting that you think is wrong.
> 
> ii. Says which version of ImageMagick you have on your system. That will be in the phpinfo page.

ok,i post the image :)

**Comment by Danack** [comment]
Yeah, I get that result when using ImageMagick 6.9.10-23.

Upgrading to ImageMagick 6.9.12-58 and recompiling Imagick makes the output image look as you would expect it.

**Comment by wilsonchen85** [comment]
ok,thank you very much,bro.
