### ISSUE TITLE
Animated image not works when using readImageFile

### ISSUE THREAD

**Issue by petersiow** [Imagick/imagick#558]
Hello, I am using Imagick to edit the animate png (.apng) files.
and here is my code.

```
$apng = file_get_contents("https://apng.onevcat.com/assets/elephant.png"); // Get APNG from Internet
$image = new Imagick(); // Init Imagick
$image->setFormat("apng"); // Set the Format to APNG
$image->readImageBlob($apng); // Load From Blob

$images = $image->coalesceImages(); // Split the frames
foreach ($images as $idx => $frame) {
    // Todo: Edit
    echo "Frame $idx Detected! <br/>";
}

/*
    Result:
    Frame 0 Detected!
    ...
    ..
    Frame 33 Detected!
*/

```

The code is work and I can do the edit.
However, the extension version is too old on the shared-hosting platform , and it is unable to read the image blob. 
So I change it to read the local file 

Here is the new code:

```
$apng = file_get_contents("https://apng.onevcat.com/assets/elephant.png"); // Get APNG from Internet

// Add: Save the files to local , to make sure the local file is same as the server one
file_put_contents("elephant.png",$apng); // Save File


$image = new Imagick(); // Init Imagick
$image->setFormat("apng"); // Set the Format to APNG

// Change: Use the saved file
$image->readImageFile(fopen("elephant.png", "rb"));


$images = $image->coalesceImages(); // Split the frames
foreach ($images as $idx => $frame) {
    // Todo: Edit
    echo "Frame $idx Detected! <br/>";
}

/*
    Result:
    Frame 0 Detected!
*/

```

It seems the `readImageFile` cannot handle the animated image, so it only return the first frame of the apng.
This problem is existing on the server (`v3.5.1 | ImageMagick 7.1.0`) and the local machine, which is the latest version ( `v3.7.0 
 | ImageMagick 7.1.0-46 `), and I checked that both version are support APNG.

Is it a bug? or I misunderstand the usage of `readImageFile` function?

**Comment by cmb69** [comment]
> However, the extension version is too old on the shared-hosting platform , and it is unable to read the image blob.

Then ask your provider to update the extension, or choose another provider.

**Comment by Danack** [comment]
@petersiow please can you attempt to recreate the issue using the ImageMagick command line tools.

Imagick is a really thin wrapper around ImageMagick. If you have found a real bug in the image processing in ImageMagick, then I'm not likely to be able to fix it in Imagick. It would need to be fixed in ImageMagick.

The upstream ImageMagick library (correctly) do no accept bug reports that involve Imagick, as they don't know about this software.

So a bug report that only involves the ImageMagick tools is far more likely to get the issue resolved than it involving Imagick.

**Comment by petersiow** [comment]
@Danack  I see, I will try to reproduce it in cli and report to them. Thanks
