### ISSUE TITLE
imagick php script fails when run with cron

### ISSUE THREAD

**Issue by BeholdersEye** [Imagick/imagick#564]
I have encountered this problem 9 years after the author posted it:

https://stackoverflow.com/questions/16318644/how-to-run-cron-job-with-php-with-imagick

Unfortunately the posted answers are at best ambiguous.

The problem seems to be related to php having different environment settings when ran as a cron job. The solution- one solution, at least, is recreating the environment variables used by imagick inside the script ran by the cron job.

That would be easier if I knew what environment variables imagick requires. $_SERVER['PATH'] alone does not seem to suffice, neither does setting the path in conjunction with set_include_path(). (In each case I print out the variables when the php script is working when served by Apache and hard code them in the cron script.)

To be certain the php / imagick code works fine when served up by apache to a browser but fails when ran as a cron job.

The cron job fails when new Imagick(); is called, which is the first imagick-related command in the php file.

The solution is probably somewhere online but difficult to find because it is hidden in a haystack of search results involving running imagemagick proper as a cron job. For example.

https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=18516

A common solution is to use wget locally to have apache serve up the webpage instead of executing the php itself with cron, as seen here:

https://stackoverflow.com/questions/2689284/executing-php-with-crontab/33428114#33428114

However that won't work in my case because the php file is stored in a folder that is not served by apache so that it is not accessible to the web.

**Comment by BeholdersEye** [comment]
get_loaded_extensions(); reveals that the imagick extension is not loaded when the php file is ran as a cron job, but is when served to a browser.

Which is likely the issue.

**Comment by BeholdersEye** [comment]
Since I observe the problem only exists in a makeshift cron install bundled with a WAMP distribution I'll go ahead and close this.

It's only tangentially related to imagick.

**Comment by Danack** [comment]
For the record, php on the command line can have a different ini file than php running in a webserver.

You probably don't have `extension=imagick.so` in the appropriate ini file. That can be found by running `php --ini`

**Comment by BeholdersEye** [comment]
That was so close to what turned out to be the solution I will thank you for your timely help- Thanks for your timely help! before I mention that it turned out to only need `extension=imagick` with no `.so` required.

Perhaps the distinction is due to being under windows, which seems to favor .dll files instead of .so files. I would still expect _some_ file extension would be a requirement but apparently not.
