### ISSUE TITLE
Imagick returns wrong image dimensions

### ISSUE THREAD

**Issue by fire1** [Imagick/imagick#566]
This image is parsed several times from PHP, and rarely PHP Imagick returns the wrong dimensions.
Where the output array from my TIF test: 

```
array:2 [
  "width" => 137
  "height" => 194
]
```

While the output from the command `file` in Linux is: 
`TIFF image data, big-endian, direntries=27, height=6000, bps=0, compression=LZW, PhotometricIntepretation=RGB, description=0522412, manufacturer=NIKON CORPORATION, model=NIKON D850, orientation=upper-left, width=4652`

> Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 
>  Debian GNU/Linux 11 (bullseye)
> PHP 8.1

Cannot upload the image since is bigger than 25mb (multilayer TIF)

**Comment by Danack** [comment]
Please can you email the image to me. Email is in my profile.

Also please post the code you are using that shows this problem.

**Comment by fire1** [comment]
@Danack you have an Email...
here is the code: `$dimensions = (new \Imagick('/mnt/fako/Test/SmPictureTest/wrong-image-size.tif'))->getImageGeometry();`
Simple as that returns the wrong size, it happens randomly

**Comment by Danack** [comment]
So....good news, I reproduced your result first try. Bad news, I'm on holiday with my shiny new MBP, and it doesn't have strace only dtrace, and I don't know how to use that...

Good news, I'm good at guessing. 

TIFF files can contain multiple images, and using this code:

```
$imagick = new Imagick(__DIR__ . '/wrong-image-size.tif');

$image_count = $imagick->getNumberImages();

echo  "There are " . $imagick->getNumberImages() . " images in this image.\n";

for ($x = 0; $x < $image_count; $x += 1) {

    $imagick->setIteratorIndex($x);

    $frame = $imagick->getImage();
    $frame_cloned = clone $frame;

    $frame_cloned->setImageFormat('png');
    $filename = "./frame_$x.png";

    $frame_cloned->writeImage($filename);

    $dimensions = $frame_cloned->getImageGeometry();

    printf(
        "For image %d dimensions are: %d, %d\n",
        $x,
        $dimensions['width'],
        $dimensions['height']
    );
}

$dimensions = $imagick->getImageGeometry();

```

I get the output:

```
php go.php
For image 0 dimensions are: 4652, 6000
For image 1 dimensions are: 4652, 6000
For image 2 dimensions are: 4652, 6000
For image 3 dimensions are: 470, 636
For image 4 dimensions are: 137, 194
```

I think the small image you are seeing is _meant_ to be a thumbnail image, but it doesn't look like one. The first three images are all quite similar to each other, though noticeably not identical as they all get output as different PNG file sizes.

I have no idea what is actually causing the problem where you mostly get the right image, and only sometimes get the wrong one. For me, it seems I always have the small image as the first image.


What I'd suggest is....

1. have a chat with whoever is supplying you with TIFF images. It could be interesting to know why there are 'almost' duplicates in there.

2. Assuming you want the biggest image, you can find that by using something similar to the code above to find the image that has the biggest detail.

3. Start googling "imagemagick Tiff order" ...I can think of a few different reasons why the ordering might not be constant. One thing would be to check the TIFF is completely valid and what the TIFF tags are set to. That you only see the 'wrong' image occasionally, and I'm seeing the wrong order constantly is quite weird.

**Comment by Danack** [comment]
Oh, also, run the TIFFs against a TIFF validator. It would be interesting to see if they are almost, but not quite, valid and so ImageMagick is guessing values where it shouldn't be.

**Comment by fire1** [comment]
> So....good news, I reproduced your result first try. Bad news, I'm on holiday with my shiny new MBP, and it doesn't have strace only dtrace, and I don't know how to use that...
> 
> Good news, I'm good at guessing.
> 
> TIFF files can contain multiple images, and using this code:
> 
> ```
> $imagick = new Imagick(__DIR__ . '/wrong-image-size.tif');
> 
> $image_count = $imagick->getNumberImages();
> 
> echo  "There are " . $imagick->getNumberImages() . " images in this image.\n";
> 
> for ($x = 0; $x < $image_count; $x += 1) {
> 
>     $imagick->setIteratorIndex($x);
> 
>     $frame = $imagick->getImage();
>     $frame_cloned = clone $frame;
> 
>     $frame_cloned->setImageFormat('png');
>     $filename = "./frame_$x.png";
> 
>     $frame_cloned->writeImage($filename);
> 
>     $dimensions = $frame_cloned->getImageGeometry();
> 
>     printf(
>         "For image %d dimensions are: %d, %d\n",
>         $x,
>         $dimensions['width'],
>         $dimensions['height']
>     );
> }
> 
> $dimensions = $imagick->getImageGeometry();
> ```
> 
> I get the output:
> 
> ```
> php go.php
> For image 0 dimensions are: 4652, 6000
> For image 1 dimensions are: 4652, 6000
> For image 2 dimensions are: 4652, 6000
> For image 3 dimensions are: 470, 636
> For image 4 dimensions are: 137, 194
> ```
> 
> I think the small image you are seeing is _meant_ to be a thumbnail image, but it doesn't look like one. The first three images are all quite similar to each other, though noticeably not identical as they all get output as different PNG file sizes.
> 
> I have no idea what is actually causing the problem where you mostly get the right image, and only sometimes get the wrong one. For me, it seems I always have the small image as the first image.
> 
> What I'd suggest is....
> 
> 1. have a chat with whoever is supplying you with TIFF images. It could be interesting to know why there are 'almost' duplicates in there.
> 2. Assuming you want the biggest image, you can find that by using something similar to the code above to find the image that has the biggest detail.
> 3. Start googling "imagemagick Tiff order" ...I can think of a few different reasons why the ordering might not be constant. One thing would be to check the TIFF is completely valid and what the TIFF tags are set to. That you only see the 'wrong' image occasionally, and I'm seeing the wrong order constantly is quite weird.

I know TIFFs are several images but didn't expect this to cause the problem, just blew my mind what is the reason for the issue...
