### ISSUE TITLE
Package connot be installed with PHP 8.1.8

### ISSUE THREAD

**Issue by DarhonSoftware** [Imagick/imagick#574]
Expected behavior

`php-pecl-imagick` can be installed

Actual behavior

`php-pecl-imagick `cannot be installed, and produces the following error:

> Problem: package php-pecl-imagick-3.7.0-1.el9.x86_64 requires php(api) = 20200930-64, but none of the providers can be installed
>   - package php-pecl-imagick-3.7.0-1.el9.x86_64 requires php(zend-abi) = 20200930-64, but none of the providers can be installed
>   - conflicting requests
>   - package php-common-8.0.20-3.el9.x86_64 is filtered out by modular filtering

I'm seeing this behavior on

    OS: AlmaLinux 9
    PHP: 8.1.8
    php-pecl-imagick: 3.7.0

Steps to reproduce, backtrace or example script

```
dnf module install php 8.1.8
dnf install php-pecl-imagick
```

**Comment by Danack** [comment]
So, that looks like an error with the packaging on AlmaLinux, which I'm not involved with. Maybe try updating your systems package info with whatever the equivalent of `apt-get update` might be?

I can at least translate the error message for you. 

`requires php(zend-abi) = 20200930-64` - says that the imagick package needs PHP 8.0, but as you have PHP 8.1 installed,.

To be clear, Imagick does compile against 8.1, and 8.2 but your package manager doesn't seem to have a version available.

**Comment by Danack** [comment]
Okay, closing as a I don't think this is a problem I can fix here.
