### ISSUE TITLE
TGA image bad orientation

### ISSUE THREAD

**Issue by TemKaSD** [Imagick/imagick#576]
Hello. I have TGA image:

![image](https://user-images.githubusercontent.com/6318282/209148357-3ca831c3-d592-4830-97f4-d7585c8d593e.png)

convert to JPG:

![image](https://user-images.githubusercontent.com/6318282/209148563-5c0665b4-4116-41bc-91dc-6e9c3591e716.png)

```
$imageTga = new \Imagick( "file.tga" );
$imageTga->setImageFormat( "jpg" );
```
This problem appeared recently, everything was fine before. What happened?

IS OK:

![image](https://user-images.githubusercontent.com/6318282/209150673-4eebf143-1e7d-4407-829f-1bd9d8d9b683.png)

Bad:

![image](https://user-images.githubusercontent.com/6318282/209150733-83181364-f885-4e8e-905d-bda4cdd88356.png)

**Comment by Danack** [comment]
Imagick doesn't actually do much image processing itself. 

It passes all of the image processing to the ImageMagick library underneath it, that does all of the work.

I can see that the two different phpinfo() have different ImageMagick versions. I guess one of them has a problem.

I'd suggest trying the command line tools of ImageMagick, and seeing if they give the same results.

```
convert file.tga file.png
```

However it is possible the issue has already been fixed in a later version of ImageMagick, as looking at https://github.com/ImageMagick/ImageMagick6/releases the current version is 6.9.12-10.

**Comment by TemKaSD** [comment]
@Danack How do I get a later version of ImageMagick for php?

**Comment by Danack** [comment]
You might be able to get a later one by updating your package manager.


You can definitely get a later version of ImageMagick 6 (the major version you are using) by downloading it from https://github.com/ImageMagick/ImageMagick6/releases

And then after extracting the package run something like:

````
./configure --with-quantum-depth=16 \
  --with-magick-plus-plus=no \
  --without-perl \
  --disable-docs \
  --with-openexr=yes \
  --with-fontconfig=yes \
  --with-fftw \
  --with-heic=yes \
  --with-jpeg=yes \
  --with-png=yes \
  --with-tiff=yes \
  --with-urw-base35-font-dir=/usr/share/fonts/type1/urw-base35 \
  --with-webp=yes
  
  make install -j8
 ```
 
 Download Imagick from https://pecl.php.net/package/imagick and then running:
 
 ```
 phpize
 ./configure
 make install -j8
 ```
 
 Imagick needs to be configured compiled and installed after a new version of ImageMagick has been installed, to make sure it works right.
 
 But I would suggest trying the convert via the command line first to make sure you can reproduce the problem just in ImageMagick itself.

**Comment by TemKaSD** [comment]
sudo convert 842974301_war3mapPreview.tga test.jpg

ImageMagick 6.9.10-23 - OK
ImageMagick 6.9.10-28 - OK
ImageMagick 6.9.10-38 - OK
ImageMagick 6.9.10-48 - OK
ImageMagick 6.9.10-58 - OK
ImageMagick 6.9.10-68 - OK
ImageMagick 6.9.10-74 - OK

ImageMagick 6.9.10-75 - BAD
ImageMagick 6.9.10-77 - BAD
ImageMagick 6.9.10-78 - BAD
ImageMagick 6.9.12-70 - BAD

Bug this code: https://github.com/ImageMagick/ImageMagick6/commit/3e322a80300f271ea9074b74110d74de4bb48fd6#diff-0b94a1b7cf3d0fcd97556cd1451faa7e7cdb1f6d9bd44b5c8b04883929bab6f8L426

**Comment by Danack** [comment]
You should open a bug at https://github.com/ImageMagick/ImageMagick6/issues I won't be able to fix it inside the Imagick code.

**Comment by TemKaSD** [comment]
Need add option -auto-orient. How do I specify this in PHP?

**Comment by Danack** [comment]
Possibly like: 
```
$image = new Imagick();

$image->setOption("-auto-orient", "1");
$image->readImage(__DIR__ . "/foo.tga");
$image->writeImage(__DIR__ . "/testing.jpg");
```

I don't have a TGA image that has rotation info in it to test against though.

Do you happen to have one that doesn't contain a middle finger salute, that you can send me?

**Comment by TemKaSD** [comment]
Is ok:
`convert 842974301_war3mapPreview.tga -auto-orient test2.jpg`

Bad:
`convert 842974301_war3mapPreview.tga test2.jpg`

Bad:
`$image->setOption("-auto-orient", "1");`

Bad:
`$image->setOption("auto-orient", "1");`

Bad:
`$image->setOption("+auto-orient", "1");`

Attach TGA:
[842974301_war3mapPreview.zip](https://github.com/Imagick/imagick/files/10305687/842974301_war3mapPreview.zip)

**Comment by Danack** [comment]
Thanks for the image.

Working code is:

```
$image = new Imagick();

$image->readImage(__DIR__ . "/orientation_test.tga");
$image->autoOrientate();
// Alternative spelling for readers of Webster's dictionary
// $image->autoOrient();

$image->writeImage(__DIR__ . "/output.jpg");
```

Apparently the "auto-orient" is only available when using the command line tools. And I realise having to call this to have the image processed correctly seems.....ungood.
