### ISSUE TITLE
Getting this error on migrating to some latest Magick lib "exception: Magick: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4470"

### ISSUE THREAD

**Issue by AbdulAzeezC** [Imagick/imagick#579]
Getting this error on migrating to some latest Magick lib "exception: Magick: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4470"

currently we are using version imageMagick version 7.1.0-2
the same issue was not observed previously, as there is no change around this code since long time in our code.

some more inputs here we are trying to draw over an image & giving inputs like below (Note that some of the getter & setters are purely our application level.
If you can kindly help with the syntax of drawableText or something is got changed in between these versions prior to above mentioned version??

std::vector<Magick::Drawable> aDrawList;
      // font
      aDrawList.push_back(DrawableFont(iImage.getDynAdFontFilePath()));
      NGN_LOG_INFORMATION("Abdul Font related issue check "<<     iImage.getDynAdFontFilePath()<<"\n"; // font color
      aDrawList.push_back(DrawableFillColor(Color(iImage.getDynAdFontColor())));
      // font size
      aDrawList.push_back(DrawablePointSize(iImage.getDynAdFontSize()));
      // text
      const double aDX=BTB_Utils::convert<double, string>(iImage.getDynAdLocationX());
      const double aDY=BTB_Utils::convert<double, string>(iImage.getDynAdLocationY());
      aDrawList.push_back(DrawableText(aDX, aDY , iPriceCurrency));

**Comment by Danack** [comment]
I think that what is happening is that ImageMagick isn't able to find the fonts, and so there isn't a font set when you try to draw some text.

You can either change how you install the software to make it be able to find your fonts, or explicitly set a font....


However, I'm going to close this issue, as I think you should report it at the https://github.com/ImageMagick/ImageMagick repo probably, and not here, as this is the repo for the PHP Imagick extension.
