### ISSUE TITLE
Cannot build with php-src master/8.3

### ISSUE THREAD

**Issue by mvorisek** [Imagick/imagick#582]
CI failure: https://github.com/mvorisek/image-php/actions/runs/4060500396/jobs/6989655041#step:13:8228

maybe related with https://github.com/Imagick/imagick/pull/423

maybe caused by https://github.com/php/php-src/commit/1fbe855971d6822921b82ae1ca312b33a1eba7c1 /cc @bwoebi

**Comment by Danack** [comment]
Please take the time to report what the issue is in a bug report, not just link to it.

That webpage isn't displaying correctly for me, and the Imagick repo builds correctly for me against php-src latest.

**Comment by mvorisek** [comment]
```
...
 PHP-Parser-4.15.1/lib/PhpParser/PrettyPrinter/
PHP-Parser-4.15.1/lib/PhpParser/PrettyPrinter/Standard.php
PHP-Parser-4.15.1/lib/PhpParser/PrettyPrinterAbstract.php
Saved /tmp/pear/temp/imagick/ImagickPixel_arginfo.h
In /tmp/pear/temp/imagick/Imagick.stub.php:
Unterminated preprocessor conditions
make: *** [Makefile:196: /tmp/pear/temp/imagick/Imagick_arginfo.h] Error 1
make: *** Waiting for unfinished jobs....
Installing header files:          /tmp/pear/temp/pear-build-defaultuserlNGJMa/install-imagick-3.7.0/usr/local/include/php/
ERROR: `make -j2 INSTALL_ROOT="/tmp/pear/temp/pear-build-defaultuserlNGJMa/install-imagick-3.7.0" install' failed
...
```

**Comment by Danack** [comment]
I don't get that error.

Can you  say what you're doing to get it?

**Comment by Danack** [comment]
I can't investigate anything I can't reproduce. btw you probably don't need to be regenerating the arginfo files, so I have no idea what you are seeing.
