### ISSUE TITLE
libjemalloc.so.2: cannot allocate memory

### ISSUE THREAD

**Issue by pascaldittmer** [Imagick/imagick#583]
Hi!
I'm on Ubuntu 20.04 with PHP FPM 8.2.1. I compiled ImageMagick from source and Imagick as well because I need the 7.1 version. I am getting the following error after restarting php:
`php-fpm8.2[1632393]: [02-Feb-2023 14:15:13] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/lib/php/20220829/imagick.so  (/lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block), /usr/lib/php/20220829/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0` 

Any ideas?

Thank you for your help.

**Comment by Danack** [comment]
Try doing `sudo ldconfig /usr/local/lib` or without the sudo.

I'm not entirely sure what that means.....but it seems to be necessary sometimes.

**Comment by Danack** [comment]
Another random thing to try:

```
Could you try the the below command before launching the notebook?

$ export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
```

But ...it sounds like maybe jemalloc and PHP extensions might not be a great fit, '[Trying to dlopen jemalloc is bad news bears.](https://github.com/jemalloc/jemalloc/issues/937)'.

So possibly compiling without jemalloc with the suggested flag is probably the easiest path.

**Comment by pascaldittmer** [comment]
Thank you for your quick response.
ldconfig did not work.
The env did not work as well.
Compiling it without jemalloc did work!
