### ISSUE TITLE
`pecl install imagick` with docker heredoc fails (wrong configure invocation?)

### ISSUE THREAD

**Issue by piotrekkr** [Imagick/imagick#584]
Hello. My original question [on SO](https://stackoverflow.com/q/75311714/1089412)

I have encountered this problem recently with docker php-fpm image when trying to install pecl extension imagick and using HEREDOC in dockerfile

```
$ cat Dockerfile-fail
# syntax=docker/dockerfile:1
FROM php:8.1.11-fpm-buster

RUN <<"EOT" bash
  echo $SHELL
  pecl install imagick
  exit 1
EOT
```
`pecl` somehow adds `exit 1` at the end of line here:
```
#9 5.168 running: /tmp/pear/temp/imagick/configure --with-php-config=/usr/local/bin/php-config --with-imagick=exit 1
```
It works fine when I change dockerfile and use shebang
```
# syntax=docker/dockerfile:1
FROM php:8.1.11-fpm-buster

RUN <<"EOT"
#!/bin/bash
echo $SHELL
pecl install imagick
exit 1
EOT
```
or `SHELL ["/bin/bash", "-ce"]` 
```
# syntax=docker/dockerfile:1
FROM php:8.1.11-fpm-buster

SHELL ["/bin/bash", "-ce"]

RUN <<"EOT"
  echo $SHELL
  pecl install imagick
  exit 1
EOT
```
Person who answered my question on SO was guessing that this may be something wrong with `phpize` / `autotools` / `configure` in `pecl`. 

Could this be the case?

**Comment by Danack** [comment]
I have absolutely no idea.

If the relevant project was shared, and could be brought up with a git checkout followed by a `docker-compose up`, I _might_ take a look, but I'm not going to investigate otherwise.

**Comment by piotrekkr** [comment]
@Danack here you go https://github.com/piotrekkr/dockerfile-imagick-build-fail just run `docker compose build`
