### ISSUE TITLE
undefined symbol: WebPMalloc

### ISSUE THREAD

**Issue by alexsoluweb** [Imagick/imagick#610]
Hi,

I have installed the required package:
`sudo apt-get update && sudo apt-get install imagemagick libwebp-dev `

I have installed imagick:
`/opt/lampp/bin/pecl install imagick`

Restarted the server and when i run any webp image with **new imagick('myimage.webp')** the server crash with this error :
`/opt/lampp/bin/httpd: symbol lookup error: /lib/x86_64-linux-gnu/libwebpmux.so.3: undefined symbol: WebPMalloc`

My environment:
Web server Xampp on php 7.4
OS Ubuntu 22.04 on the latest stable kernel

Any idea please?

**Comment by alexsoluweb** [comment]
Hi Danack,

First of thanks for your fast support help. I tried almost all day yesterday to resolve it with no luck.

Yes it is readable:
```
$ ll /lib/x86_64-linux-gnu/libwebpmux.so.3
lrwxrwxrwx 1 root root 19 Mar 14  2022 /lib/x86_64-linux-gnu/libwebpmux.so.3 -> libwebpmux.so.3.0.8
```

_Can you check that the version of libwebpmux is the same as libwebp-dev that ImageMagick is compiled against? aka, could there be some shenanigans either with multiple versions of libwebp on your system, or a version being replaced after a reboot?_

Im not sure how to check this properly so i asked ChatGPT and this is what he proposed to me:
```
$ dpkg -l | grep libwebp
ii  libwebp-dev:amd64                          1.2.2-2                                        amd64        Lossy compression of digital photographic images
ii  libwebp7:amd64                             1.2.2-2                                        amd64        Lossy compression of digital photographic images
ii  libwebpdemux2:amd64                        1.2.2-2                                        amd64        Lossy compression of digital photographic images.
ii  libwebpmux3:amd64                          1.2.2-2                                        amd64        Lossy compression of digital photographic images

$ ldd /lib/x86_64-linux-gnu/libwebpmux.so.3 | grep libwebp.so
        libwebp.so.7 => /lib/x86_64-linux-gnu/libwebp.so.7 (0x00007fea81f9d000)
$ dpkg -s libwebp-dev | grep Version
Version: 1.2.2-2
```

When i run convert and resize any webp it is working properly like so:
`convert assets/images/myimage.webp -resize 100x100 test.webp`


Thanks again!

**Comment by Danack** [comment]
> When i run convert and resize on any webp it is working properly directly with imagemagick

Okay, that's moderately surprising. It seems that the library that contains WebPMalloc must be on your system.

Can you try running your PHP code through the command line and seeing if that works?

**Comment by Danack** [comment]
Did you get it working? 

If yes, then letting me know what the problem was would be good, so I can tell other people.

If no, then I'm going to close the issue unless you provide more info.
