### ISSUE TITLE
Imagick extension not working

### ISSUE THREAD

**Issue by ashokmahal** [Imagick/imagick#611]
we have started using ext-imagick-php8.2-nts-x64 for an application called redcap. We have a version upgrade recently and post that we are receiving and error mentioned below.

Imagick extension not working: The Imagick PHP extension, while enabled, gives an error that REDCap doesn't know how to handle. Until this is fixed, rendering of inline PDFs in descriptive fields will not work. The error message returned was:

RegistryKeyLookupFailed `CoderModulesPath' @ error/module.c/GetMagickModulePath/667

**Comment by ashokmahal** [comment]
Can anyone  help me with the issue

**Comment by Danack** [comment]
Anyone could. But to set your expectations, I don't know, and I've almost never seen any users actually help on an issue that doesn't affect them directly.

You should probably either:

* sponsor the ImageMagick people, so they have spare bandwidth for investigating things like you're seeing.
* report a bug with whoever provided you with Imagick/ImageMagick. The bug you're seeing isn't in the code...probably. It's more likely to be in how it was compiled or some missing setting.
* try googling the error message.


In the meantime, here is some music.

https://www.youtube.com/watch?v=8Kc-YPqW4k0&ab_channel=FelipeNIN

**Comment by ashokmahal** [comment]
Thanks Danack. We have downgraded to PHP 8.1 which is standard for imagick version. It has sorted the issue
