### ISSUE TITLE
download of php-imagick v3.7.0 via Pecl is broken

### ISSUE THREAD

**Issue by szaimen** [Imagick/imagick#629]
Hi, when I try to download php-imagick v3.7.0 via PECL, I get a 500 error.

You can try it yourself: https://pecl.php.net/get/imagick-3.7.0.tgz. 

Not sure where to report this to..

**Comment by zbigniew-malcherczyk-tg** [comment]
It seems like it's fixed now...

**Comment by szaimen** [comment]
Indeed. That was fast, thanks!
