### ISSUE TITLE
convert -help gives "missing required argument" at the end

### ISSUE THREAD

**Issue by Spanni26** [Imagick/imagick#635]
When calling convert 7.1.1-19 with "-help", it gives an error at the end:

with an image format name and a colon (i.e. ps:image) or specify the
image type as the filename suffix (i.e. image.ps).  Specify 'file' as
'-' for standard input or output.
convert: missing required argument  @ error/convert.c/ConvertImageCommand/562.
It exits with 130.

In my opinion it should give back the usage, nothing more. On 7.1.0-9 there is no error message and it exists with 0.

**Comment by Danack** [comment]
If you're using ImageMagick on the command line, you probably want to report bugs over here: https://github.com/ImageMagick/ImageMagick

This repository is for the PHP Imagick extension, which doesn't expose any command line tools.

**Comment by Spanni26** [comment]
Thanks...my fault.
