### ISSUE TITLE
 "NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/746" in PHP 8.2 and PHP 8.3

### ISSUE THREAD

**Issue by TonyCBE** [Imagick/imagick#648]
$image = new Imagick();
	try {
         $image->readImage($path . $file);
        }
	catch (ImagickException $e)
    	{
         schrijf_log('Error reading image: ' . $e->getMessage());
        }

generates  "NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/746" in PHP versions 8.2 and 8.3.

No issue in version 8.1

**Comment by Danack** [comment]
Then you'll probably need to ask your hosting provider to investigate the problem, or get them to report an issue here. I don't have any way of figuring out how a machine is misconfigured.

**Comment by TonyCBE** [comment]
Logged the issue at hosting provider

**Comment by Danack** [comment]
Well, good luck.
