### ISSUE TITLE
Can't install via pecl on php 8.3

### ISSUE THREAD

**Issue by Kabingeran** [Imagick/imagick#667]
Can't install via pecl on php 8.3.4 and Alpine

**Comment by HQuest** [comment]
So this is "not planned" as in won't work with Alpine, won't work with PHP 8.3, won't install via pecl, or lack of clarity? Just got imagemagick updated to 7.1.1_30 and in the process of updating imagick to 3.7.0 via pecl upgrade, it fails as follows (tested against PHP v8.3.4):

> Saved /tmp/pear/temp/imagick/ImagickDraw_arginfo.h
> Parse /tmp/pear/temp/imagick/ImagickPixelIterator.stub.php to generate /tmp/pear/temp/imagick/ImagickPixelIterator_arginfo.h
> Saved /tmp/pear/temp/imagick/ImagickPixelIterator_arginfo.h
> Parse /tmp/pear/temp/imagick/ImagickPixel.stub.php to generate /tmp/pear/temp/imagick/ImagickPixel_arginfo.h
> Saved /tmp/pear/temp/imagick/ImagickPixel_arginfo.h
> Parse /tmp/pear/temp/imagick/Imagick.stub.php to generate /tmp/pear/temp/imagick/Imagick_arginfo.h
> In /tmp/pear/temp/imagick/Imagick.stub.php:
> Unterminated preprocessor conditions
> make: *** [Makefile:196: /tmp/pear/temp/imagick/Imagick_arginfo.h] Error 1
> ERROR: `make INSTALL_ROOT="/tmp/pear/temp/pear-build-rootmGvNVN/install-imagick-3.7.0" install' failed
