### ISSUE TITLE
Help wanted: why are ImageMagick 7.1.0-13 cached builds failing?

### ISSUE THREAD

**Issue by Danack** [Imagick/imagick#679]
What appears to be happening is this: 

* The initial build against 7.1.0-13 works - https://github.com/Imagick/imagick/actions/runs/9750276748/job/26909346504
* All the built files are then cached, using the github cache action.
* subsequent builds that use the cache fail - https://github.com/Imagick/imagick/actions/runs/9750276748/job/26909659087

The error message is:

> PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/lib/php/20210902/imagick.so (libwebpdemux.so.2: cannot open shared object file: No such file or directory), 

libwebpdemux is the library file for handling webp image files.

For some reason, although that can be found by ImageMagick when that is being compiled and can be found when running the tests on the uncached job, it can't be found when Imagick tries to load ImageMagick and the linked libwebpdemux.so.2 on the cached job.

btw, there is a chance that running `ldconfig /usr/local/lib` or something might be the solution.

**Comment by mvorisek** [comment]
@iluuu1994, you are an php CI expert, maybe you know?

**Comment by iluuu1994** [comment]
Not off the top of my head, sorry.

**Comment by Danack** [comment]
Turns out it was a mismatch between the OS used to build ImageMagick and then cache it, and the OS version that uses the cached ImageMagick.
