### ISSUE TITLE
Issue iOS18 HEIC image s previewing

### ISSUE THREAD

**Issue by polocto** [Imagick/imagick#702]
I am sorry I so some related issues already closed Imagick/imagick#675. I am a new to nextcloud and I would like to update libheif to be able to preview HEIC images from iOS 18 but cannot find out how to update it. I already tried to update php-imagick but it is not solving my issue.

**Comment by kostirez1** [comment]
I'm not sure which way run your Nextcloud instance, but `php-imagick` uses dynamic linking to load the `libheif` library. So you have to update that using your distros package manager.

For example, on Debian Bookworm, the latest `libheif1` package is version `1.15.1-1+deb12u1` and `1.18+` is what you need. Therefore, the only option right now is to enable [Debian backports repo](https://backports.debian.org/Instructions/), which contains `1.19.3-1~bpo12+1`.

Once you enable backports and `apt install libheif1/bookworm-backports`, image decoding of iOS 18 HEIF format starts working. 👍

**Comment by polocto** [comment]
Thank you that was it, I didn't new how to install libheif last version.
